// GENERATED by scripts/gen-hex-geometry.ts. Do not edit by hand.
//
// Axis-aligned bounding box of every published part, in the PRINT orientation
// the mesh ships in: the minimum corner and the size, in millimetres. The packer
// needs both -- the size to place, the minimum corner to turn a target position
// into the translation that gets it there. `z0` is not always zero (one part's
// mesh rests 0.144 mm above the bed), which is why the 3MF writer translates by
// `-z0` instead of assuming a part is already seated.
//
// REGENERATE THIS IN THE SAME COMMIT that re-cuts the meshes and bumps
// HEX_RELEASE and HEX_PART_SLUGS:
//
//   pnpm tsx scripts/gen-hex-geometry.ts
//
// A stale table packs against sizes the meshes no longer have. The symptom is
// parts overlapping on a plate in someone else's slicer, and nothing about that
// points back at a committed data file -- so the rule is gated rather than
// trusted: `__tests__/hex-geometry.test.ts` holds this table to HEX_PART_SLUGS
// and the stamp below to HEX_RELEASE.
//
// Every size here was cross-checked at generation time against `printBboxMm` in
// the hex-cluster manifest, which is the same geometry taken from the FreeCAD
// solid rather than from the mesh. A table that agrees with itself and with
// nothing else cannot get committed.
//
// The second table is the published SPELLING of each part, which the 3MF writer
// puts on the `<object>` so a slicer's object list reads `Hex-TB-Main` rather
// than `hex-tb-main`. It is recoverable at generation time and nowhere else.
import type { PartBox } from "@/lib/hex-plate";

/** The mesh release these boxes were measured from.
 *
 *  Pinned to HEX_RELEASE by the guard test. It catches the half of staleness
 *  this file cannot notice on its own: a release bumped without the generator
 *  being re-run leaves every number here describing the previous cut. */
export const HEX_GEOMETRY_RELEASE = "2026-08-03";

export const HEX_PART_BOX: Record<string, PartBox> = {
  "dovetail-cap-double-f-1h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-2h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-3h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-solid": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-m-1h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-2h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-3h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-solid": { x0: -35.841, y0: 0, z0: 0, dx: 71.682, dy: 25, dz: 4 },
  "dovetail-cap-single-f-1h": { x0: -18.405, y0: -25, z0: 0, dx: 36.809, dy: 25, dz: 5 },
  "dovetail-cap-single-f-solid": { x0: -18.405, y0: -25, z0: 0, dx: 36.809, dy: 25, dz: 5 },
  "dovetail-cap-single-m-1h": { x0: -17.255, y0: 0, z0: 0, dx: 34.51, dy: 25, dz: 4 },
  "dovetail-cap-single-m-solid": { x0: -17.255, y0: 0, z0: 0, dx: 34.51, dy: 25, dz: 4 },
  "hex-tb-carrier-bot-parts-tray": { x0: -36.229, y0: -33.5, z0: 0, dx: 72.457, dy: 31, dz: 19.667 },
  "hex-tb-carrier-bot-parts-tray-lid": { x0: -28.013, y0: -24.897, z0: 0, dx: 56.025, dy: 15.093, dz: 10 },
  "hex-tb-carrier-bot-solid": { x0: -36.229, y0: -33.5, z0: 0, dx: 72.457, dy: 31, dz: 6 },
  "hex-tb-carrier-left-parts-tray": { x0: -33.814, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 19.667 },
  "hex-tb-carrier-left-parts-tray-lid": { x0: -22.954, y0: -29.274, z0: 0, dx: 13.677, dy: 58.548, dz: 10 },
  "hex-tb-carrier-left-solid": { x0: -33.814, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 6 },
  "hex-tb-carrier-parts-tray": { x0: -38.682, y0: -33.5, z0: 0, dx: 77.365, dy: 67, dz: 15 },
  "hex-tb-carrier-parts-tray-lid": { x0: -27.497, y0: -23.844, z0: 0, dx: 54.994, dy: 47.688, dz: 10 },
  "hex-tb-carrier-right-parts-tray": { x0: 2.367, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 19.667 },
  "hex-tb-carrier-right-parts-tray-lid": { x0: 9.277, y0: -29.274, z0: 0, dx: 13.677, dy: 58.548, dz: 10 },
  "hex-tb-carrier-right-solid": { x0: 2.367, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 6 },
  "hex-tb-carrier-solid": { x0: -38.682, y0: -33.5, z0: 0, dx: 77.365, dy: 67, dz: 3 },
  "hex-tb-carrier-top-parts-tray": { x0: -37.383, y0: 0.5, z0: 0, dx: 74.767, dy: 33, dz: 19.667 },
  "hex-tb-carrier-top-parts-tray-lid": { x0: -31.013, y0: 7.854, z0: 0, dx: 62.025, dy: 17.043, dz: 10 },
  "hex-tb-carrier-top-solid": { x0: -37.383, y0: 0.5, z0: 0, dx: 74.767, dy: 33, dz: 6 },
  "hex-tb-corner-f-solid": { x0: -21.621, y0: -33.615, z0: 0, dx: 43.242, dy: 37.615, dz: 30 },
  "hex-tb-corner-m-solid": { x0: -14.875, y0: -25.764, z0: 0, dx: 29.75, dy: 27.764, dz: 30 },
  "hex-tb-half-bot-1h": { x0: -39.976, y0: -40, z0: 0, dx: 79.951, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-2h": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-3h": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-solid": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-left-1h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-2h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-3h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-solid": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-right-1h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-2h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-3h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-solid": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-top-1h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-2h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-3h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-solid": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-main": { x0: -43.879, y0: -40, z0: 0, dx: 87.757, dy: 78, dz: 33 },
  "hex-tb-spike-ball-joint": { x0: 0, y0: -41.135, z0: 0.144, dx: 32, dy: 6.95, dz: 7.765 },
  "hex-tb-spike-ball-platform-solid": { x0: -21.651, y0: -25, z0: 0, dx: 43.301, dy: 50, dz: 7.5 },
  "hex-tb-spike-ball-zip-1h": { x0: -21.651, y0: -25, z0: 0, dx: 43.301, dy: 50, dz: 7.5 },
  "hex-tb-spike-ball-zip-single": { x0: -8.66, y0: -10, z0: 0, dx: 17.321, dy: 20, dz: 11.598 },
  "hex-tb-spike-platform-lrg": { x0: -40, y0: 22.572, z0: 0, dx: 36, dy: 31.177, dz: 26.5 },
  "hex-tb-spike-platform-sm": { x0: -32, y0: 29.5, z0: 0, dx: 20, dy: 17.321, dz: 26.5 },
  "hex-tb-spike-solid": { x0: 0, y0: -40.91, z0: 0, dx: 25, dy: 6.725, dz: 7.765 },
};

/** The PUBLISHED spelling of each part -- what a slicer shows in its object list
 *  once a plate is opened.
 *
 *  Kept here because this is the only place it survives. The slug is a LOSSY
 *  projection of the filename (lowercased, with everything outside
 *  `[a-z0-9.-]` collapsed to a hyphen), so `hex-tb-main` cannot be turned back
 *  into `Hex-TB-Main` by any rule -- only looked up. Measured against the
 *  known-good reference plate: all 15 names survive a Creality Print round trip,
 *  and carrying them is the whole argument for 3MF over STL.
 *
 *  A SEPARATE table rather than a field on the box, because `PartBox` is the
 *  geometry the packer needs and a name is not geometry. Sharing a row would not
 *  protect the pairing anyway -- a wrong name in the right row is still a wrong
 *  name. What protects it is the guard test that runs every name back through
 *  the R2 uploader's own `slug()` and insists it lands on its own key. */
export const HEX_PART_NAME: Record<string, string> = {
  "dovetail-cap-double-f-1h": "Dovetail-Cap-Double-F-1H",
  "dovetail-cap-double-f-2h": "Dovetail-Cap-Double-F-2H",
  "dovetail-cap-double-f-3h": "Dovetail-Cap-Double-F-3H",
  "dovetail-cap-double-f-solid": "Dovetail-Cap-Double-F-Solid",
  "dovetail-cap-double-m-1h": "Dovetail-Cap-Double-M-1H",
  "dovetail-cap-double-m-2h": "Dovetail-Cap-Double-M-2H",
  "dovetail-cap-double-m-3h": "Dovetail-Cap-Double-M-3H",
  "dovetail-cap-double-m-solid": "Dovetail-Cap-Double-M-Solid",
  "dovetail-cap-single-f-1h": "Dovetail-Cap-Single-F-1H",
  "dovetail-cap-single-f-solid": "Dovetail-Cap-Single-F-Solid",
  "dovetail-cap-single-m-1h": "Dovetail-Cap-Single-M-1H",
  "dovetail-cap-single-m-solid": "Dovetail-Cap-Single-M-Solid",
  "hex-tb-carrier-bot-parts-tray": "Hex-TB-Carrier-Bot-Parts-Tray",
  "hex-tb-carrier-bot-parts-tray-lid": "Hex-TB-Carrier-Bot-Parts-Tray-Lid",
  "hex-tb-carrier-bot-solid": "Hex-TB-Carrier-Bot-Solid",
  "hex-tb-carrier-left-parts-tray": "Hex-TB-Carrier-Left-Parts-Tray",
  "hex-tb-carrier-left-parts-tray-lid": "Hex-TB-Carrier-Left-Parts-Tray-Lid",
  "hex-tb-carrier-left-solid": "Hex-TB-Carrier-Left-Solid",
  "hex-tb-carrier-parts-tray": "Hex-TB-Carrier-Parts-Tray",
  "hex-tb-carrier-parts-tray-lid": "Hex-TB-Carrier-Parts-Tray-Lid",
  "hex-tb-carrier-right-parts-tray": "Hex-TB-Carrier-Right-Parts-Tray",
  "hex-tb-carrier-right-parts-tray-lid": "Hex-TB-Carrier-Right-Parts-Tray-Lid",
  "hex-tb-carrier-right-solid": "Hex-TB-Carrier-Right-Solid",
  "hex-tb-carrier-solid": "Hex-TB-Carrier-Solid",
  "hex-tb-carrier-top-parts-tray": "Hex-TB-Carrier-Top-Parts-Tray",
  "hex-tb-carrier-top-parts-tray-lid": "Hex-TB-Carrier-Top-Parts-Tray-Lid",
  "hex-tb-carrier-top-solid": "Hex-TB-Carrier-Top-Solid",
  "hex-tb-corner-f-solid": "Hex-TB-Corner-F-Solid",
  "hex-tb-corner-m-solid": "Hex-TB-Corner-M-Solid",
  "hex-tb-half-bot-1h": "Hex-TB-Half-Bot-1H",
  "hex-tb-half-bot-2h": "Hex-TB-Half-Bot-2H",
  "hex-tb-half-bot-3h": "Hex-TB-Half-Bot-3H",
  "hex-tb-half-bot-solid": "Hex-TB-Half-Bot-Solid",
  "hex-tb-half-left-1h": "Hex-TB-Half-Left-1H",
  "hex-tb-half-left-2h": "Hex-TB-Half-Left-2H",
  "hex-tb-half-left-3h": "Hex-TB-Half-Left-3H",
  "hex-tb-half-left-solid": "Hex-TB-Half-Left-Solid",
  "hex-tb-half-right-1h": "Hex-TB-Half-Right-1H",
  "hex-tb-half-right-2h": "Hex-TB-Half-Right-2H",
  "hex-tb-half-right-3h": "Hex-TB-Half-Right-3H",
  "hex-tb-half-right-solid": "Hex-TB-Half-Right-Solid",
  "hex-tb-half-top-1h": "Hex-TB-Half-Top-1H",
  "hex-tb-half-top-2h": "Hex-TB-Half-Top-2H",
  "hex-tb-half-top-3h": "Hex-TB-Half-Top-3H",
  "hex-tb-half-top-solid": "Hex-TB-Half-Top-Solid",
  "hex-tb-main": "Hex-TB-Main",
  "hex-tb-spike-ball-joint": "Hex-TB-Spike-Ball-Joint",
  "hex-tb-spike-ball-platform-solid": "Hex-TB-Spike-Ball-Platform-Solid",
  "hex-tb-spike-ball-zip-1h": "Hex-TB-Spike-Ball-Zip-1H",
  "hex-tb-spike-ball-zip-single": "Hex-TB-Spike-Ball-Zip-Single",
  "hex-tb-spike-platform-lrg": "Hex-TB-Spike-Platform-Lrg",
  "hex-tb-spike-platform-sm": "Hex-TB-Spike-Platform-Sm",
  "hex-tb-spike-solid": "Hex-TB-Spike-Solid",
};
