// GENERATED by scripts/gen-hex-geometry.ts. Do not edit by hand.
//
// Axis-aligned bounding box of every published part, in the PRINT orientation
// the mesh ships in: the minimum corner and the size, in millimetres. The packer
// needs both -- the size to place, the minimum corner to turn a target position
// into the translation that gets it there. `z0` is not always zero (one part's
// mesh rests 0.144 mm above the bed), which is why the 3MF writer translates by
// `-z0` instead of assuming a part is already seated.
//
// REGENERATE THIS IN THE SAME COMMIT that re-cuts the meshes and bumps
// HEX_RELEASE and HEX_PART_SLUGS:
//
//   pnpm tsx scripts/gen-hex-geometry.ts
//
// A stale table packs against sizes the meshes no longer have. The symptom is
// parts overlapping on a plate in someone else's slicer, and nothing about that
// points back at a committed data file -- so the rule is gated rather than
// trusted: `__tests__/hex-geometry.test.ts` holds this table to HEX_PART_SLUGS
// and the stamp below to HEX_RELEASE.
//
// Every size here was cross-checked at generation time against `printBboxMm` in
// the hex-cluster manifest, which is the same geometry taken from the FreeCAD
// solid rather than from the mesh. A table that agrees with itself and with
// nothing else cannot get committed.
import type { PartBox } from "@/lib/hex-plate";

/** The mesh release these boxes were measured from.
 *
 *  Pinned to HEX_RELEASE by the guard test. It catches the half of staleness
 *  this file cannot notice on its own: a release bumped without the generator
 *  being re-run leaves every number here describing the previous cut. */
export const HEX_GEOMETRY_RELEASE = "2026-08-03";

export const HEX_PART_BOX: Record<string, PartBox> = {
  "dovetail-cap-double-f-1h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-2h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-3h": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-f-solid": { x0: -35.5, y0: -25, z0: 0, dx: 71, dy: 25, dz: 5 },
  "dovetail-cap-double-m-1h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-2h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-3h": { x0: -35.846, y0: 0, z0: 0, dx: 71.692, dy: 25, dz: 4 },
  "dovetail-cap-double-m-solid": { x0: -35.841, y0: 0, z0: 0, dx: 71.682, dy: 25, dz: 4 },
  "dovetail-cap-single-f-1h": { x0: -18.405, y0: -25, z0: 0, dx: 36.809, dy: 25, dz: 5 },
  "dovetail-cap-single-f-solid": { x0: -18.405, y0: -25, z0: 0, dx: 36.809, dy: 25, dz: 5 },
  "dovetail-cap-single-m-1h": { x0: -17.255, y0: 0, z0: 0, dx: 34.51, dy: 25, dz: 4 },
  "dovetail-cap-single-m-solid": { x0: -17.255, y0: 0, z0: 0, dx: 34.51, dy: 25, dz: 4 },
  "hex-tb-carrier-bot-parts-tray": { x0: -36.229, y0: -33.5, z0: 0, dx: 72.457, dy: 31, dz: 19.667 },
  "hex-tb-carrier-bot-parts-tray-lid": { x0: -28.013, y0: -24.897, z0: 0, dx: 56.025, dy: 15.093, dz: 10 },
  "hex-tb-carrier-bot-solid": { x0: -36.229, y0: -33.5, z0: 0, dx: 72.457, dy: 31, dz: 6 },
  "hex-tb-carrier-left-parts-tray": { x0: -33.814, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 19.667 },
  "hex-tb-carrier-left-parts-tray-lid": { x0: -22.954, y0: -29.274, z0: 0, dx: 13.677, dy: 58.548, dz: 10 },
  "hex-tb-carrier-left-solid": { x0: -33.814, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 6 },
  "hex-tb-carrier-parts-tray": { x0: -38.682, y0: -33.5, z0: 0, dx: 77.365, dy: 67, dz: 15 },
  "hex-tb-carrier-parts-tray-lid": { x0: -27.497, y0: -23.844, z0: 0, dx: 54.994, dy: 47.688, dz: 10 },
  "hex-tb-carrier-right-parts-tray": { x0: 2.367, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 19.667 },
  "hex-tb-carrier-right-parts-tray-lid": { x0: 9.277, y0: -29.274, z0: 0, dx: 13.677, dy: 58.548, dz: 10 },
  "hex-tb-carrier-right-solid": { x0: 2.367, y0: -33.875, z0: 0, dx: 31.447, dy: 67.75, dz: 6 },
  "hex-tb-carrier-solid": { x0: -38.682, y0: -33.5, z0: 0, dx: 77.365, dy: 67, dz: 3 },
  "hex-tb-carrier-top-parts-tray": { x0: -37.383, y0: 0.5, z0: 0, dx: 74.767, dy: 33, dz: 19.667 },
  "hex-tb-carrier-top-parts-tray-lid": { x0: -31.013, y0: 7.854, z0: 0, dx: 62.025, dy: 17.043, dz: 10 },
  "hex-tb-carrier-top-solid": { x0: -37.383, y0: 0.5, z0: 0, dx: 74.767, dy: 33, dz: 6 },
  "hex-tb-corner-f-solid": { x0: -21.621, y0: -33.615, z0: 0, dx: 43.242, dy: 37.615, dz: 30 },
  "hex-tb-corner-m-solid": { x0: -14.875, y0: -25.764, z0: 0, dx: 29.75, dy: 27.764, dz: 30 },
  "hex-tb-half-bot-1h": { x0: -39.976, y0: -40, z0: 0, dx: 79.951, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-2h": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-3h": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-bot-solid": { x0: -39.976, y0: -40, z0: 0, dx: 79.952, dy: 39.875, dz: 35 },
  "hex-tb-half-left-1h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-2h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-3h": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-left-solid": { x0: -43.879, y0: -40, z0: 0, dx: 43.754, dy: 78, dz: 35 },
  "hex-tb-half-right-1h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-2h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-3h": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-right-solid": { x0: -1.875, y0: -40, z0: 0, dx: 45.754, dy: 78, dz: 35 },
  "hex-tb-half-top-1h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-2h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-3h": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-half-top-solid": { x0: -43.879, y0: -1.875, z0: 0, dx: 87.757, dy: 39.875, dz: 35 },
  "hex-tb-main": { x0: -43.879, y0: -40, z0: 0, dx: 87.757, dy: 78, dz: 33 },
  "hex-tb-spike-ball-joint": { x0: 0, y0: -41.135, z0: 0.144, dx: 32, dy: 6.95, dz: 7.765 },
  "hex-tb-spike-ball-platform-solid": { x0: -21.651, y0: -25, z0: 0, dx: 43.301, dy: 50, dz: 7.5 },
  "hex-tb-spike-ball-zip-1h": { x0: -21.651, y0: -25, z0: 0, dx: 43.301, dy: 50, dz: 7.5 },
  "hex-tb-spike-ball-zip-single": { x0: -8.66, y0: -10, z0: 0, dx: 17.321, dy: 20, dz: 11.598 },
  "hex-tb-spike-platform-lrg": { x0: -40, y0: 22.572, z0: 0, dx: 36, dy: 31.177, dz: 26.5 },
  "hex-tb-spike-platform-sm": { x0: -32, y0: 29.5, z0: 0, dx: 20, dy: 17.321, dz: 26.5 },
  "hex-tb-spike-solid": { x0: 0, y0: -40.91, z0: 0, dx: 25, dy: 6.725, dz: 7.765 },
};
