// GENERATED by scripts/gen-hex-support-data.ts. Do not edit by hand.
//
// Launch readiness 4.7. Source: hex-cluster build/support-data-2026-10-01.json
// (otd-hex-support-data/1), the owner's calibration slice (4.4) in
// Creality Print 7.2.1.5476 with no settings.
// HEX_SUPPORT_DATA_HASH is this file's content hash (sha256 of this text,
// LF line endings, the hash line's value blanked); the test recomputes it.
//
// Rows: every RELEASED part the slicer flagged, and only those. Every other
// released part was sliced and raised nothing, so it needs neither support
// nor a brim. 297 parts sliced: 5 support, 3 brim, 0 both.

/** Content hash of this file. See the header. */
export const HEX_SUPPORT_DATA_HASH = "19cc4273853a60c65f37e67d9c37f84fe80fa6faf43f7dcf7894a297e2c72e0b";

/** Where the rows came from. */
export const HEX_SUPPORT_SOURCE = {
  format: "otd-hex-support-data/1",
  release: "2026-10-01",
  file: "support-data-2026-10-01.json",
  /** sha256 of the input, LF line endings. */
  sha256: "3182fea72ff03b1ca34a57712f2953a484e8b55573362e5a649ba558deab128c",
  slicerWarnings: "build/slicer-warnings-2026-10-01.json",
  slicerWarningsSha256: "8533ed038898902415f42e818db65a6cacdd6e1ffdce6dca3a9e8e5e134a7d5d",
  slicer: "Creality Print 7.2.1.5476",
} as const;

/** The counts over every part sliced, released or not. */
export const HEX_SUPPORT_COUNTS = {
  parts: 297,
  support: 5,
  brim: 3,
  both: 0,
} as const;

/** Decision 1.4: the profile the slice was judged against. */
export const HEX_SUPPORT_PROFILE = {
  material: "PETG",
  nozzleMm: 0.4,
  layerMm: 0.2,
  walls: 4,
  infillPattern: "adaptive cubic",
  infillDensityPct: 30,
  alsoWorks: [
    { nozzleMm: 0.6, layerMm: 0.3 },
  ],
} as const;

/** One row per released part that needs support, a brim, or both. `note` is
 *  completed after the part's label. Sorted by slug. */
export const HEX_SUPPORT_ROWS: readonly {
  readonly slug: string;
  readonly support: boolean;
  readonly brim: boolean;
  readonly warnings: readonly string[];
  readonly firstLayerMm2: number;
  readonly note: string;
}[] = [
  {
    slug: "25mm-ins-trinity-handle",
    support: true,
    brim: false,
    warnings: ["floating cantilever"],
    firstLayerMm2: 1322.19,
    note:
      "needs support switched on: the slicer reports a floating cantilever. It stands on about 1322 sq mm, so adhesion is not the problem.",
  },
  {
    slug: "25mm-ins-zip",
    support: true,
    brim: false,
    warnings: ["floating regions"],
    firstLayerMm2: 339.64,
    note:
      "needs support switched on: the slicer reports floating regions. It stands on about 340 sq mm, so adhesion is not the problem.",
  },
  {
    slug: "hex-half-w",
    support: true,
    brim: false,
    warnings: ["floating cantilever"],
    firstLayerMm2: 2172.3,
    note:
      "needs support switched on: the slicer reports a floating cantilever. It stands on about 2172 sq mm, so adhesion is not the problem.",
  },
  {
    slug: "hex-quarter-nw",
    support: true,
    brim: false,
    warnings: ["floating cantilever"],
    firstLayerMm2: 1956.18,
    note:
      "needs support switched on: the slicer reports a floating cantilever. It stands on about 1956 sq mm, so adhesion is not the problem.",
  },
  {
    slug: "hex-quarter-sw",
    support: true,
    brim: false,
    warnings: ["floating cantilever"],
    firstLayerMm2: 1390.03,
    note:
      "needs support switched on: the slicer reports a floating cantilever. It stands on about 1390 sq mm, so adhesion is not the problem.",
  },
  {
    slug: "hex-spike-stud",
    support: false,
    brim: true,
    warnings: [],
    firstLayerMm2: 106.57,
    note:
      "give it a brim: it stands on about 107 sq mm, which the slicer judges too little to hold it on its own.",
  },
  {
    slug: "pvc-section-double",
    support: false,
    brim: true,
    warnings: [],
    firstLayerMm2: 22.5,
    note:
      "give it a brim: it stands on about 23 sq mm, which the slicer judges too little to hold it on its own.",
  },
  {
    slug: "pvc-section-single",
    support: false,
    brim: true,
    warnings: [],
    firstLayerMm2: 11.25,
    note:
      "give it a brim: it stands on about 11 sq mm, which the slicer judges too little to hold it on its own.",
  },
];
