// GENERATED by scripts/gen-hex-geometry.ts. Do not edit by hand.
//
// What each published part LOOKS LIKE from above, and what CLASS of part it is.
// Both exist for one reader: the 3MF package thumbnail (`src/lib/hex-thumbnail.ts`),
// which used to draw every part as its bounding box and therefore drew a hex
// tile, a carrier tray and a dovetail cap as three rectangles differing only in
// aspect ratio.
//
// A SEPARATE FILE FROM `hex-geometry.ts`, deliberately. That table is MIRRORED
// by the configurator (`bs-cap-hex/src/hex/hex-geometry.ts`) and compared against
// this repo's copy by a test over there, so every field it carries is a field
// that repo has to carry too. None of this is geometry the packer needs, so
// putting it in the same object would make a second repo track a table it does
// not read, and trip its drift guard on a change that cannot affect it.
//
// THE OUTLINE IS A TRUE SILHOUETTE, not a convex hull. The hull of a carrier
// tray and the hull of a solid hex tile are the same hexagon; the silhouette
// keeps the dovetail notches cut INTO a tile and the dovetail tabs standing OUT
// of a tray, which is the difference you can actually see at 256 px. It is the
// union of the up-facing triangles projected to XY -- exactly the part's
// vertical shadow -- traced off a 0.1 mm raster and simplified to 0.35 mm, which
// is sub-pixel at every bed size the endpoint accepts (the most magnified is a
// 100 mm bed at 2.44 px/mm).
//
// WHAT A SHADOW LOSES, stated plainly because it is not recoverable from the
// data: depth. A pocket that does not go all the way through casts no shadow, so
// a tray reads as solid inside its own rim, and the 1H/2H/3H variants of a half
// tile are drawn identically because their holes are blind. Through-holes DO
// survive -- the dovetail caps' fastener holes are real rings below.
//
// Coordinates are integers 0..1000: PER-MILLE of the part's own bounding box on
// each axis, with y measured from the box's MINIMUM corner the same way
// `PartBox` is. So the drawing code needs no millimetres -- it already knows
// where the footprint landed and how big it is. Rings are closed implicitly (the
// last point joins the first) and are filled EVEN-ODD, under which a ring inside
// a ring is a hole however either is wound.
//
// REGENERATE THIS IN THE SAME COMMIT that re-cuts the meshes and bumps
// HEX_RELEASE and HEX_PART_SLUGS -- it comes out of the same command as
// `hex-geometry.ts`:
//
//   pnpm tsx scripts/gen-hex-geometry.ts
//
// Every outline here was checked at generation time against three things it
// could not satisfy by accident: that it reaches all four sides of its own
// bounding box, that it covers a believable share of it, and that it costs fewer
// than 200 points. `__tests__/hex-outlines.test.ts` holds the tables to
// HEX_PART_SLUGS and the stamp below to HEX_RELEASE.
import type { HexPartFamily } from "@/lib/hex-parts";

/** The mesh release these outlines were traced from. Pinned to HEX_RELEASE by
 *  the guard test, for the same reason HEX_GEOMETRY_RELEASE is: a release bumped
 *  without the generator being re-run leaves every shape here describing the
 *  previous cut. */
export const HEX_OUTLINE_RELEASE = "2026-08-17";

/** Outline coordinates run 0..this, on both axes, across the part's own bounding
 *  box. Exported so the drawing code divides by the number the generator
 *  multiplied by, rather than by its own copy of it. */
export const HEX_OUTLINE_SCALE = 1000;

/** What class of part each slug is. See `HexPartFamily` for the vocabulary and
 *  `familyOf()` in the generator for the rules -- which have NO catch-all, so a
 *  part this table does not name is a part the generator refused to write. */
export const HEX_PART_FAMILY: Record<string, HexPartFamily> = {
  "dovetail-cap-double-f-1h": "cap",
  "dovetail-cap-double-f-2h": "cap",
  "dovetail-cap-double-f-3h": "cap",
  "dovetail-cap-double-f-solid": "cap",
  "dovetail-cap-double-m-1h": "cap",
  "dovetail-cap-double-m-2h": "cap",
  "dovetail-cap-double-m-3h": "cap",
  "dovetail-cap-double-m-solid": "cap",
  "dovetail-cap-single-f-1h": "cap",
  "dovetail-cap-single-f-solid": "cap",
  "dovetail-cap-single-m-1h": "cap",
  "dovetail-cap-single-m-solid": "cap",
  "hex-tb-carrier-bot-parts-tray": "insert",
  "hex-tb-carrier-bot-parts-tray-lid": "pcb",
  "hex-tb-carrier-bot-solid": "insert",
  "hex-tb-carrier-left-parts-tray": "insert",
  "hex-tb-carrier-left-parts-tray-lid": "pcb",
  "hex-tb-carrier-left-solid": "insert",
  "hex-tb-carrier-parts-tray": "insert",
  "hex-tb-carrier-parts-tray-lid": "pcb",
  "hex-tb-carrier-right-parts-tray": "insert",
  "hex-tb-carrier-right-parts-tray-lid": "pcb",
  "hex-tb-carrier-right-solid": "insert",
  "hex-tb-carrier-solid": "insert",
  "hex-tb-carrier-top-parts-tray": "insert",
  "hex-tb-carrier-top-parts-tray-lid": "pcb",
  "hex-tb-carrier-top-solid": "insert",
  "hex-tb-corner-f-solid": "cap",
  "hex-tb-corner-m-solid": "cap",
  "hex-tb-half-bot-1h": "base",
  "hex-tb-half-bot-2h": "base",
  "hex-tb-half-bot-3h": "base",
  "hex-tb-half-bot-solid": "base",
  "hex-tb-half-left-1h": "base",
  "hex-tb-half-left-2h": "base",
  "hex-tb-half-left-3h": "base",
  "hex-tb-half-left-solid": "base",
  "hex-tb-half-right-1h": "base",
  "hex-tb-half-right-2h": "base",
  "hex-tb-half-right-3h": "base",
  "hex-tb-half-right-solid": "base",
  "hex-tb-half-top-1h": "base",
  "hex-tb-half-top-2h": "base",
  "hex-tb-half-top-3h": "base",
  "hex-tb-half-top-solid": "base",
  "hex-tb-main": "base",
  "hex-tb-spike-ball-joint": "spike",
  "hex-tb-spike-ball-platform-solid": "accessory",
  "hex-tb-spike-ball-zip-1h": "accessory",
  "hex-tb-spike-ball-zip-single": "accessory",
  "hex-tb-spike-platform-lrg": "spike",
  "hex-tb-spike-platform-sm": "spike",
  "hex-tb-spike-solid": "spike",
};

/** Each part's top-down outline, as closed rings of `x, y, x, y, ...` integers
 *  in 0..HEX_OUTLINE_SCALE.
 *
 *  FLAT NUMBERS rather than points, because the fill loop walks them in pairs
 *  and an array of two-element arrays would be 1000 small objects the garbage
 *  collector has to care about, per request, for no gain in readability at this
 *  density. */
export const HEX_PART_OUTLINE: Record<string, readonly (readonly number[])[]> = {
  "dovetail-cap-double-f-1h": [[0,0,1000,0,1000,1000,0,1000], [490,260,456,292,432,352,418,432,415,528,427,624,448,692,476,732,510,740,544,708,566,652,582,568,585,472,573,376,554,312,524,268]],
  "dovetail-cap-double-f-2h": [[0,0,1000,0,1000,1000,0,1000], [208,260,175,292,151,352,137,432,134,528,145,624,166,692,194,732,228,740,262,708,285,652,300,568,303,472,292,376,272,312,242,268], [772,260,738,292,714,352,700,432,697,528,708,624,730,692,758,732,792,740,825,708,848,652,863,568,866,472,855,376,835,312,806,268]],
  "dovetail-cap-double-f-3h": [[0,0,1000,0,1000,1000,0,1000], [208,260,175,292,151,352,137,432,134,528,145,624,166,692,194,732,228,740,262,708,285,652,300,568,303,472,292,376,272,312,242,268], [490,260,456,292,432,352,418,432,415,528,427,624,448,692,476,732,510,740,544,708,566,652,582,568,585,472,573,376,554,312,524,268], [772,260,738,292,714,352,700,432,697,528,708,624,730,692,758,732,792,740,825,708,848,652,863,568,866,472,855,376,835,312,806,268]],
  "dovetail-cap-double-f-solid": [[0,0,1000,0,1000,1000,0,1000]],
  "dovetail-cap-double-m-1h": [[0,0,1000,0,1000,1000,0,1000], [490,260,455,296,431,360,418,440,417,540,431,640,450,696,477,732,509,740,538,716,565,656,582,560,583,460,572,372,550,304,523,268]],
  "dovetail-cap-double-m-2h": [[0,0,1000,0,1000,1000,0,1000], [211,260,176,296,152,360,139,440,138,540,152,640,172,696,198,732,230,740,259,716,285,660,303,560,304,460,293,372,271,304,244,268], [768,260,734,296,710,360,697,440,696,540,710,640,729,696,756,732,788,740,817,716,844,656,861,560,862,460,851,372,828,304,802,268]],
  "dovetail-cap-double-m-3h": [[0,0,1000,0,1000,1000,0,1000], [211,260,176,296,152,360,139,440,138,540,152,640,172,696,198,732,230,740,259,716,285,660,303,560,304,460,293,372,271,304,244,268], [490,260,455,296,431,360,418,440,417,540,431,640,450,696,477,732,509,740,538,716,565,656,582,560,583,460,572,372,550,304,523,268], [768,260,734,296,710,360,697,440,696,540,710,640,729,696,756,732,788,740,817,716,844,656,861,560,862,460,851,372,828,304,802,268]],
  "dovetail-cap-double-m-solid": [[0,0,1000,0,1000,1000,0,1000]],
  "dovetail-cap-single-f-1h": [[0,0,1000,0,1000,1000,0,1000], [481,260,416,292,372,348,342,432,337,528,359,624,399,692,454,732,519,740,579,712,628,652,658,568,663,472,641,376,603,312,546,268]],
  "dovetail-cap-single-f-solid": [[0,0,1000,0,1000,1000,0,1000]],
  "dovetail-cap-single-m-1h": [[0,0,1000,0,1000,1000,0,1000], [478,260,406,296,357,360,330,440,328,540,357,640,397,696,452,732,519,740,580,716,632,660,670,560,672,460,649,372,603,304,548,268]],
  "dovetail-cap-single-m-solid": [[0,0,1000,0,1000,1000,0,1000]],
  "hex-tb-carrier-bot-parts-tray": [[161,0,279,0,279,58,441,58,441,0,559,0,559,58,721,58,721,0,839,0,839,58,999,65,767,1000,614,1000,586,935,586,832,581,819,419,819,414,832,414,939,388,1000,233,1000,1,65,161,58]],
  "hex-tb-carrier-bot-parts-tray-lid": [[155,0,845,0,1000,1000,0,1000]],
  "hex-tb-carrier-bot-solid": [[161,0,279,0,279,58,441,58,441,0,559,0,559,58,721,58,721,0,839,0,839,58,999,65,767,1000,614,1000,586,935,583,819,418,819,414,939,388,1000,233,1000,1,65,161,58]],
  "hex-tb-carrier-left-parts-tray": [[459,0,924,0,939,7,939,139,1000,139,1000,264,939,264,939,437,1000,437,1000,563,939,563,939,736,1000,736,1000,861,939,861,939,993,924,1000,459,1000,0,634,45,593,178,593,194,586,191,410,45,407,0,366]],
  "hex-tb-carrier-left-parts-tray-lid": [[431,0,1000,0,1000,1000,431,1000,0,827,0,173]],
  "hex-tb-carrier-left-solid": [[459,0,924,0,939,7,939,139,1000,139,1000,264,939,264,939,437,1000,437,1000,563,939,563,939,736,1000,736,1000,861,939,861,939,993,924,1000,459,1000,0,634,45,593,178,593,194,586,191,410,45,407,0,366]],
  "hex-tb-carrier-parts-tray": [[249,0,394,0,420,30,420,78,425,84,576,84,581,78,581,28,606,0,753,4,1000,501,751,1000,606,1000,580,970,580,922,575,916,424,916,419,922,419,972,394,1000,247,996,0,499]],
  "hex-tb-carrier-parts-tray-lid": [[249,0,751,0,875,245,998,505,751,1000,249,1000,125,755,0,499]],
  "hex-tb-carrier-right-parts-tray": [[76,0,541,0,1000,366,955,407,822,407,806,414,809,590,955,593,1000,634,541,1000,76,1000,61,993,61,861,0,861,0,736,61,736,61,563,0,563,0,437,61,437,61,264,0,264,0,139,61,139,61,7]],
  "hex-tb-carrier-right-parts-tray-lid": [[0,0,569,0,1000,173,1000,827,569,1000,0,1000]],
  "hex-tb-carrier-right-solid": [[76,0,541,0,1000,366,955,407,822,407,806,414,809,590,955,593,1000,634,541,1000,76,1000,61,993,61,861,0,861,0,736,61,736,61,563,0,563,0,437,61,437,61,264,0,264,0,139,61,139,61,7]],
  "hex-tb-carrier-solid": [[249,0,394,0,420,30,422,84,579,84,581,28,606,0,753,4,1000,501,751,1000,606,1000,580,970,578,916,421,916,419,972,394,1000,247,996,0,499]],
  "hex-tb-carrier-top-parts-tray": [[241,0,390,0,416,58,418,170,580,170,583,61,610,0,759,0,999,945,828,945,828,1000,714,1000,714,945,557,945,557,1000,443,1000,443,945,286,945,286,1000,172,1000,172,945,1,945]],
  "hex-tb-carrier-top-parts-tray-lid": [[0,0,1000,6,842,1000,158,1000]],
  "hex-tb-carrier-top-solid": [[241,0,390,0,416,58,418,170,580,170,583,61,610,0,759,0,999,945,828,945,828,1000,714,1000,714,945,557,945,557,1000,443,1000,443,945,286,945,286,1000,172,1000,172,945,1,945]],
  "hex-tb-corner-f-solid": [[25,0,675,0,698,17,995,523,1000,800,975,833,811,840,749,1000,634,1000,590,870,558,833,25,833,0,800,0,33]],
  "hex-tb-corner-m-solid": [[30,0,617,0,651,17,1000,433,1000,800,963,833,735,840,644,1000,477,1000,409,863,366,833,37,833,7,810,0,30]],
  "hex-tb-half-bot-1h": [[269,0,394,0,394,50,606,50,606,0,731,0,836,368,846,378,854,353,864,358,960,692,960,709,943,714,941,732,998,922,999,947,600,950,600,1000,400,1000,400,950,1,947,3,922,59,732,58,714,40,709,40,692,136,358,146,353,154,378,164,368]],
  "hex-tb-half-bot-2h": [[269,0,394,0,394,50,606,50,606,0,731,0,836,368,846,378,854,353,864,358,960,692,960,709,943,714,941,732,998,922,999,947,600,950,600,1000,400,1000,400,950,1,947,3,922,59,732,58,714,40,709,40,692,136,358,146,353,154,378,164,368]],
  "hex-tb-half-bot-3h": [[269,0,394,0,394,50,606,50,606,0,731,0,836,368,846,378,854,353,864,358,960,692,960,709,943,714,941,732,998,922,999,947,600,950,600,1000,400,1000,400,950,1,947,3,922,59,732,58,714,40,709,40,692,136,358,146,353,154,378,164,368]],
  "hex-tb-half-bot-solid": [[269,0,394,0,394,50,606,50,606,0,731,0,836,368,846,378,854,353,864,358,960,692,960,709,943,714,941,732,998,922,999,947,600,950,600,1000,400,1000,400,950,1,947,3,922,59,732,58,714,40,709,40,692,136,358,146,353,154,378,164,368]],
  "hex-tb-half-left-1h": [[580,0,808,0,808,26,1000,29,1000,401,938,406,957,408,957,618,934,618,1000,623,993,1000,820,1000,820,974,422,974,311,867,313,858,340,858,347,849,167,673,151,662,123,676,110,672,0,565,196,374,192,364,160,360,180,336,338,183,352,179,370,194,384,192]],
  "hex-tb-half-left-2h": [[580,0,808,0,808,26,1000,29,1000,401,938,406,957,408,957,438,427,438,957,440,957,586,427,587,957,587,957,618,934,619,1000,623,993,1000,820,1000,820,974,422,974,311,867,313,858,340,858,347,849,167,673,151,662,123,676,110,672,0,565,196,374,192,364,160,360,180,336,338,183,352,179,370,194,384,192]],
  "hex-tb-half-left-3h": [[580,0,808,0,808,26,1000,29,1000,401,938,406,957,408,957,618,934,618,1000,623,993,1000,820,1000,820,974,422,974,311,867,313,858,340,858,347,849,167,673,151,662,123,676,110,672,0,565,196,374,192,364,160,360,180,336,338,183,352,179,370,194,384,192]],
  "hex-tb-half-left-solid": [[580,0,808,0,808,26,1000,29,1000,401,938,406,957,408,957,438,427,438,957,440,957,586,427,587,957,587,957,618,934,619,1000,623,993,1000,820,1000,820,974,422,974,311,867,313,858,340,858,347,849,167,673,151,662,123,676,110,672,0,565,196,374,192,364,160,360,180,336,338,183,352,179,370,194,384,192]],
  "hex-tb-half-right-1h": [[227,0,448,1,472,28,336,29,474,29,633,192,646,194,664,179,677,183,847,356,838,365,817,364,812,374,1000,565,954,612,924,612,952,614,895,672,882,676,856,662,841,673,668,849,675,858,701,858,703,867,596,974,216,974,216,1000,50,1000,116,996,44,996,44,619,638,619,0,615,627,613,0,612,0,414,627,414,0,413,4,408,638,408,44,406,44,29,227,26]],
  "hex-tb-half-right-2h": [[227,0,448,1,472,28,336,29,474,29,633,192,646,194,664,179,677,183,847,356,838,365,817,364,812,374,1000,565,954,612,924,612,952,614,895,672,882,676,856,662,841,673,668,849,675,858,701,858,703,867,596,974,216,974,216,1000,50,1000,116,996,44,996,44,619,638,619,0,615,627,613,0,612,0,414,627,414,0,413,4,408,638,408,44,406,44,29,227,26]],
  "hex-tb-half-right-3h": [[227,0,448,1,472,28,336,29,474,29,633,192,646,194,664,179,677,183,847,356,838,365,817,364,812,374,1000,565,954,612,924,612,952,614,895,672,882,676,856,662,841,673,668,849,675,858,701,858,703,867,596,974,216,974,216,1000,50,1000,116,996,44,996,44,619,638,619,0,615,627,613,0,612,0,414,627,414,0,413,4,408,638,408,44,406,44,29,227,26]],
  "hex-tb-half-right-solid": [[227,0,448,1,472,28,336,29,474,29,633,192,646,194,664,179,677,183,847,356,838,365,817,364,812,374,1000,565,954,612,924,612,952,614,895,672,882,676,856,662,841,673,668,849,675,858,701,858,703,867,596,974,216,974,216,1000,50,1000,116,996,44,996,44,619,638,619,0,615,627,613,0,612,0,414,627,414,0,413,4,408,638,408,44,406,44,29,227,26]],
  "hex-tb-half-top-1h": [[39,0,403,0,403,50,597,50,597,0,961,0,1000,150,945,358,938,366,932,341,921,343,828,699,828,717,844,722,845,739,789,950,591,950,591,1000,409,1000,409,950,208,945,155,739,156,722,173,712,155,634,79,343,68,341,62,366,55,358,0,150]],
  "hex-tb-half-top-2h": [[39,0,403,0,403,50,597,50,597,0,961,0,1000,150,945,358,938,366,932,341,921,343,828,699,828,717,844,722,845,739,789,950,591,950,591,1000,409,1000,409,950,208,945,155,739,156,722,173,712,155,634,79,343,68,341,62,366,55,358,0,150]],
  "hex-tb-half-top-3h": [[39,0,403,0,403,50,597,50,597,0,961,0,1000,150,945,358,938,366,932,341,921,343,828,699,828,717,844,722,845,739,789,950,591,950,591,1000,409,1000,409,950,208,945,155,739,156,722,173,712,155,634,79,343,68,341,62,366,55,358,0,150]],
  "hex-tb-half-top-solid": [[39,0,403,0,403,50,597,50,597,0,961,0,1000,150,945,358,938,366,932,341,921,343,828,699,828,717,844,722,845,739,789,950,591,950,591,1000,409,1000,409,950,208,945,155,739,156,722,173,712,155,634,79,343,68,341,62,366,55,358,0,150]],
  "hex-tb-main": [[289,0,403,0,405,5,711,0,809,192,818,192,827,179,842,203,920,356,916,365,904,364,902,374,1000,565,945,672,938,676,925,662,912,682,827,850,830,858,844,858,845,867,789,974,591,974,591,1000,409,1000,409,974,211,974,155,867,156,858,170,858,173,850,88,682,75,662,62,676,52,668,0,563,98,374,96,364,84,365,80,356,158,203,173,179,182,192,191,192], [405,6,400,18,403,26,597,26,600,21,595,6]],
  "hex-tb-spike-ball-joint": [[888,0,944,29,978,143,1000,357,994,600,928,857,822,786,803,1000,750,1000,747,929,47,929,19,814,0,543,9,271,47,157,750,157,772,29,850,86]],
  "hex-tb-spike-ball-platform-solid": [[499,0,1000,250,1000,750,501,1000,0,750,0,250]],
  "hex-tb-spike-ball-zip-1h": [[499,0,1000,250,1000,750,501,1000,0,750,0,250]],
  "hex-tb-spike-ball-zip-single": [[497,0,1000,250,1000,750,873,760,965,770,503,1000,35,770,127,760,0,750,0,250,127,240,35,230]],
  "hex-tb-spike-platform-lrg": [[250,0,750,0,778,51,1000,503,750,1000,250,1000,222,949,0,497]],
  "hex-tb-spike-platform-sm": [[250,0,750,0,910,312,1000,503,750,1000,250,1000,90,688,0,497]],
  "hex-tb-spike-solid": [[988,0,1000,1000,960,1000,956,925,60,925,28,836,0,522,4,299,52,134,960,134]],
};
