"use client";

// The L1.01 Gerber set as an exploded stack, drawn from the REAL answer-key files.
//
// Teaching point: "export gerbers" produces one flat drawing per fabrication layer,
// and those eight drawings pressed together in this order ARE the board. Its
// sibling, GerberLayerStack, makes the same point with abstract slabs and typed
// layer names; this one makes it with the actual geometry the fab would build, so
// the claim is demonstrated rather than asserted. Every path comes from
// data/l101-gerber-layers.ts, generated by scripts/gen-l101-gerber-data.ts.
//
// CLASS: Plate (diagram-standards.md, Two classes). Depth is load-bearing here --
// the lesson is that eight sheets get pressed together in an order, and a flat
// frame would make that claim false.
//
// MOTION: Tier P (animation-standards.md). useScrollParallax writes --p; the sheets
// spread apart as the figure moves off centre AND the front sheets give up alpha as
// they go, so the inner planes come into view. Two deliberate departures from the
// written standards, both noted at the call sites below:
//   1. the Tier-P read path is documented as transform-only; this also reads
//      `opacity`. Both are compositor properties, so the reason for that rule (no
//      re-render, no layout, CLS 0) is untouched.
//   2. rule P4 forbids group `opacity` for depth dimming because a filled object
//      then stops occluding what is behind it. That IS the effect here.
// --p unset resolves every var(--p,0) to 0, so SSR, no-JS, reduced motion and the
// raster exporter all get the settled frame -- which is why the settled frame is
// already part-faded (SETTLED below) rather than a closed stack.
import { type CSSProperties } from "react";
import { DiagramFrame } from "./DiagramFrame";
import { useScrollParallax } from "./useScrollParallax";
import { BOARD, SHEETS } from "./data/l101-gerber-layers";

// ── projection ────────────────────────────────────────────────────────────────
// Owner-picked over eight sandbox rounds (H3). The board's length runs right and
// down 20 degrees, its width recedes up-right at 30 degrees with no
// foreshortening. Screen y is down, so an upward axis takes a negative component.
const LD = -20, WD = 30, WF = 1;
const rad = (deg: number) => (deg * Math.PI) / 180;
const LV: [number, number] = [Math.cos(rad(LD)) * BOARD.h, -Math.sin(rad(LD)) * BOARD.h];
const WV: [number, number] = [Math.cos(rad(WD)) * WF * BOARD.w, -Math.sin(rad(WD)) * WF * BOARD.w];
const XS = [0, LV[0], WV[0], LV[0] + WV[0]];
const YS = [0, LV[1], WV[1], LV[1] + WV[1]];
const MIN_X = Math.min(...XS), MIN_Y = Math.min(...YS);
const P_W = Math.max(...XS) - MIN_X;   // one sheet's screen width
const P_H = Math.max(...YS) - MIN_Y;   // one sheet's screen height
// matrix(a,b,c,d,e,f) maps board (x,y) -> (a x + c y + e, b x + d y + f)
const MAT = [WV[0] / BOARD.w, WV[1] / BOARD.w, LV[0] / BOARD.h, LV[1] / BOARD.h] as const;

// Copper reads as solid metal, so it is drawn thicker than the mask and silk
// coatings -- the same material rule the sibling GerberLayerStack uses.
const T_CU = 1.97, T_FILM = 1.18;
const N = SHEETS.length;

// wide (desktop + print) and narrow (phone) layouts. The narrow form separates the
// sheets fully and runs tall: a phone has no print-aspect budget, and rule P10
// wants the same world re-composed rather than summarised into text cards.
// The wide gutter is a real legend column, not padding: at the tight gap that
// keeps the stack reading as a stack, the eight sheet anchors span only a third of
// the art's height, so the labels are spread evenly over the full height instead
// and a leader carries the eye back to the sheet each one names.
const WIDE = { gap: 5, gut: 100, spread: 9, leaders: true };
const NARROW = { gap: 13, gut: 30, spread: 5, leaders: false };

// Front sheets give up this much alpha at full spread, and this fraction of it is
// already given up at rest -- so the exported raster is an x-ray too, not a closed
// stack that hides everything the diagram is about.
const FADE_MAX = 0.85;
const SETTLED = 0.4;

const f = (n: number): number => {
  const v = Math.round(n * 100) / 100;
  return Object.is(v, -0) ? 0 : v;
};
const rank = (i: number) => (i - (N - 1) / 2) / ((N - 1) / 2); // -1 front .. +1 back
const thickOf = (kind: string) => (kind === "cu" ? T_CU : T_FILM);
// Only sheets IN FRONT occlude what is behind them, so only they need to fade.
const fadeOf = (i: number) => Math.max(0, -rank(i)) * FADE_MAX;

// ── geometry, built once at module scope ─────────────────────────────────────
// Every sheet's paths are defined ONCE in a hidden <defs> and both layouts pull
// them in with <use>, so the 195 KB of real geometry is in the document a single
// time instead of twice.
//
// The markup below is injected with dangerouslySetInnerHTML, as the sibling
// GerberLayerStack does. It is safe by construction and must stay that way: every
// string is a module-scope constant built from committed, generated geometry, and
// NOTHING here reads a prop, a URL, or any other runtime input. If this ever needs
// to interpolate a value that did not come from the generator, it stops being
// injectable and has to be built as real elements instead.
const DEFS = `<defs>
<clipPath id="gs-clip"><path d="${BOARD.outline}"/></clipPath>
${SHEETS.map(
  (s) =>
    `<g id="gs-${s.id}">${s.paths
      .map((p) =>
        p.kind === "stroke"
          ? `<path class="gs-${s.kind}-s" d="${p.d}" stroke-width="${p.width}"/>`
          : `<path class="gs-${s.kind}-f" d="${p.d}"/>`,
      )
      .join("")}</g>`,
).join("\n")}
</defs>`;

function stackMarkup(gap: number): string {
  const order = SHEETS.map((s, i) => ({ s, i })).sort((a, b) => b.i - a.i); // back first
  return order
    .map(({ s, i }) => {
      const t = thickOf(s.kind);
      const oy = -MIN_Y + i * gap;
      const ox = -MIN_X;
      // the extruded body: a front face along the board's near edge, a side face
      // along its far end, both in the same projection as the top face
      const front = `M0,0 l${f(LV[0])},${f(LV[1])} v${f(t)} l${f(-LV[0])},${f(-LV[1])} Z`;
      const side = `M${f(LV[0])},${f(LV[1])} l${f(WV[0])},${f(WV[1])} v${f(t)} l${f(-WV[0])},${f(-WV[1])} Z`;
      const fade = f(fadeOf(i));
      const base = f((s.kind === "cu" ? 1 : 0.86) * (1 - fade * SETTLED));
      return (
        `<g class="gs-sheet gs-${s.kind} gs-d${i}" style="--k:${f(rank(i))};--fade:${fade};--base:${base}">` +
        `<g transform="translate(${f(ox)},${f(oy)})">` +
        `<path class="gs-body" d="${front}"/><path class="gs-shade" d="${front}"/>` +
        `<path class="gs-body" d="${side}"/><path class="gs-shade2" d="${side}"/></g>` +
        `<g transform="matrix(${f(MAT[0])},${f(MAT[1])},${f(MAT[2])},${f(MAT[3])},${f(ox)},${f(oy)})">` +
        `<path class="gs-substrate" d="${BOARD.outline}"/>` +
        `<g clip-path="url(#gs-clip)"><use href="#gs-${s.id}"/></g>` +
        `<path class="gs-edge" d="${BOARD.outline}"/>` +
        `</g></g>`
      );
    })
    .join("");
}

function box(gap: number, gut: number) {
  const pad = 1.5;
  const w = P_W + gut;
  const h = P_H + gap * (N - 1) + T_CU;
  return { w, h, viewBox: `${-pad} ${-pad} ${f(w + pad * 2)} ${f(h + pad * 2)}`, pad };
}

// Where each sheet's label sits and, when leaders are on, where it points back to.
// Both the SVG leader and the HTML label read this, so they cannot drift apart.
function labelGeometry(gap: number, gut: number, even: boolean) {
  const { w, h, pad } = box(gap, gut);
  const inset = h * 0.05;
  return SHEETS.map((s, i) => {
    const t = thickOf(s.kind);
    // the near edge is the sheet's BOTTOM; its mass runs up by P_H, so centre on that
    const anchorY = -MIN_Y + i * gap + t / 2 - P_H / 2;
    const y = even ? inset + (i * (h - inset * 2)) / (N - 1) : anchorY;
    const x = P_W + 3;
    return {
      anchorX: P_W,
      anchorY,
      x,
      y,
      left: `${f(((x + pad) / (w + pad * 2)) * 100)}%`,
      top: `${f(((y + pad) / (h + pad * 2)) * 100)}%`,
    };
  });
}

function leaderMarkup(gap: number, gut: number, even: boolean): string {
  const g = labelGeometry(gap, gut, even);
  return g
    .map(
      ({ anchorX, anchorY, x, y }, i) =>
        `<path class="gs-leader" style="--k:${f(rank(i))}" fill="none" ` +
        `d="M${f(anchorX)},${f(anchorY)} H${f(x - 4)} L${f(x - 1)},${f(y)} h2"/>`,
    )
    .join("");
}

const WIDE_BOX = box(WIDE.gap, WIDE.gut);
const NARROW_BOX = box(NARROW.gap, NARROW.gut);
const WIDE_MARKUP = stackMarkup(WIDE.gap) + leaderMarkup(WIDE.gap, WIDE.gut, WIDE.leaders);
const NARROW_MARKUP = stackMarkup(NARROW.gap);
const WIDE_LABELS = labelGeometry(WIDE.gap, WIDE.gut, WIDE.leaders);
const NARROW_LABELS = labelGeometry(NARROW.gap, NARROW.gut, NARROW.leaders);

function Labels({
  pos,
  cls,
  pinned,
}: {
  pos: { left: string; top: string }[];
  cls: string;
  /** an evenly-spread label is pinned to the gutter, so it must not ride --p */
  pinned: boolean;
}) {
  return (
    <div className={`gs-labels ${cls}`} aria-hidden="true">
      {SHEETS.map((s, i) => (
        <span
          key={s.id}
          className={`gs-label${pinned ? " gs-label-pinned" : ""}`}
          style={{ "--k": f(rank(i)), left: pos[i].left, top: pos[i].top } as CSSProperties}
        >
          {s.tag ? <i className="gs-tag">{s.tag}</i> : null}
          <b>{s.name}</b>
          <em>{s.gloss}</em>
        </span>
      ))}
    </div>
  );
}

export function L101GerberStack({ caption }: { caption?: string }) {
  const ref = useScrollParallax<HTMLDivElement>();
  return (
    <DiagramFrame
      eyebrow="GERBER · THE REAL SET"
      tone="gold"
      title="Peel the board apart"
      ariaLabel="The L1.01 board drawn as an exploded stack of its eight Gerber layers, each one rendered from the actual exported file. Front to back: F_Silk, the white labels; F_Mask, the solder mask with an opening at every pad; F_Cu, layer 1, carrying your traces; In1_Cu and In2_Cu, layers 2 and 3, the two inner copper ground planes; B_Cu, layer 4, the back-side traces; then B_Mask and B_Silk. The front sheets are drawn part-transparent so the copper underneath shows through. Eight flat drawings, pressed together in this order, are the board the fab builds."
      caption={caption}
      defaultCaption="Every sheet here is drawn from the actual exported file. Eight flat drawings, pressed together in this order, are the board."
    >
      <style>{CSS}</style>
      <div className="gs-art" ref={ref}>
        <svg className="gs-defs" width="0" height="0" aria-hidden="true" dangerouslySetInnerHTML={{ __html: DEFS }} />

        {/* desktop + print */}
        <div className="gs-form gs-wide">
          <svg
            className="gs-svg"
            viewBox={WIDE_BOX.viewBox}
            preserveAspectRatio="xMidYMid meet"
            aria-hidden="true"
            style={{ "--spread": `${WIDE.spread}px` } as CSSProperties}
            dangerouslySetInnerHTML={{ __html: WIDE_MARKUP }}
          />
          <Labels pos={WIDE_LABELS} cls="gs-lw" pinned={WIDE.leaders} />
        </div>

        {/* phone: the same stack, separated further and running tall */}
        <div className="gs-form gs-narrow">
          <svg
            className="gs-svg"
            viewBox={NARROW_BOX.viewBox}
            preserveAspectRatio="xMidYMid meet"
            aria-hidden="true"
            style={{ "--spread": `${NARROW.spread}px` } as CSSProperties}
            dangerouslySetInnerHTML={{ __html: NARROW_MARKUP }}
          />
          <Labels pos={NARROW_LABELS} cls="gs-ln" pinned={NARROW.leaders} />
        </div>
      </div>
    </DiagramFrame>
  );
}

const CSS = `
.gs-art{position:relative;
  /* the silkscreen is white ink on a dark board, so on the ivory page it needs a
     deepened value of its own: a token would flip it to page-ink black and a fixed
     pale would vanish. Same physical-material exception the sibling stack takes. */
  --gs-ink:#d7d0bf;}
:root[data-theme="light"] .gs-art{--gs-ink:#8c8472;}
.gs-defs{position:absolute;width:0;height:0;overflow:hidden;}
.gs-form{position:relative;}
.gs-svg{display:block;width:100%;height:auto;overflow:hidden;}
.gs-narrow{display:none;}

/* Tier-P binding. --pa is the magnitude of --p, so the stack opens the same amount
   whichever way the figure is off centre. Only transform and opacity read it. */
.gs-sheet{--pa:max(var(--p,0),calc(-1 * var(--p,0)));--base:1;--fade:0;
  transform:translateY(calc(var(--p,0) * var(--k) * var(--spread,9px)));
  opacity:calc(var(--base) - var(--pa) * var(--fade));}

/* materials: copper and mask are tokens so they re-theme; silk is the ink above */
.gs-substrate{fill:var(--color-navy-dark,#1a1a2e);}
.gs-edge{fill:none;stroke:var(--color-title,#f1ece0);stroke-width:.3;opacity:.5;stroke-linejoin:round;}
.gs-cu-f{fill:var(--color-command-gold,#c8963e);}
.gs-cu-s{fill:none;stroke:var(--color-command-gold,#c8963e);stroke-linecap:round;stroke-linejoin:round;}
.gs-mask-f{fill:var(--color-signal-blue,#4a8fff);}
.gs-mask-s{fill:none;stroke:var(--color-signal-blue,#4a8fff);stroke-linecap:round;stroke-linejoin:round;}
.gs-silk-f{fill:var(--gs-ink);}
.gs-silk-s{fill:none;stroke:var(--gs-ink);stroke-linecap:round;stroke-linejoin:round;}
.gs-body{fill:var(--color-navy-dark,#1a1a2e);}
.gs-cu .gs-body{fill:var(--color-command-gold,#c8963e);}
.gs-mask .gs-body{fill:var(--color-signal-blue,#4a8fff);}
.gs-silk .gs-body{fill:var(--gs-ink);}
.gs-shade{fill:#000;opacity:.34;} .gs-shade2{fill:#000;opacity:.5;}
/* depth dim: the further back a sheet sits, the less of its own colour it keeps */
.gs-d3{fill-opacity:.95;} .gs-d4{fill-opacity:.9;} .gs-d5{fill-opacity:.85;}
.gs-d6{fill-opacity:.8;} .gs-d7{fill-opacity:.75;}
.gs-d3 .gs-substrate,.gs-d4 .gs-substrate,.gs-d5 .gs-substrate,
.gs-d6 .gs-substrate,.gs-d7 .gs-substrate,
.gs-d3 .gs-shade,.gs-d4 .gs-shade,.gs-d5 .gs-shade,.gs-d6 .gs-shade,.gs-d7 .gs-shade,
.gs-d3 .gs-shade2,.gs-d4 .gs-shade2,.gs-d5 .gs-shade2,.gs-d6 .gs-shade2,.gs-d7 .gs-shade2{fill-opacity:1;}

/* labels are HTML over the art (rule P1): % placement so they track the geometry,
   real px type so they never scale under the floor */
.gs-labels{position:absolute;inset:0;pointer-events:none;}
.gs-label{position:absolute;display:flex;align-items:baseline;gap:.32rem;white-space:nowrap;
  translate:0 -50%;
  transform:translateY(calc(var(--p,0) * var(--k) * var(--spread,9px)));}
.gs-label-pinned{transform:none;}
/* leader: the sheet end rides the spread, the gutter end stays put, so the line
   stretches rather than detaching (rule P7, anchors derive from their object) */
.gs-leader{stroke:var(--color-panel-border,#3a3f50);stroke-width:.45;stroke-linejoin:round;
  transform:translateY(calc(var(--p,0) * var(--k) * var(--spread,9px) * .5));}
.gs-label b{font-family:var(--font-mono,"Space Mono",monospace);font-weight:700;
  font-size:clamp(.9rem,2.3vw,1rem);color:var(--color-title,#f1ece0);}
.gs-label em{font-family:var(--font-mono,"Space Mono",monospace);font-style:normal;
  font-size:clamp(.8rem,2vw,.88rem);color:var(--color-muted,#aaa);}
.gs-tag{font-family:var(--font-mono,"Space Mono",monospace);font-style:normal;font-weight:700;
  font-size:.7rem;letter-spacing:.08em;color:var(--color-command-gold,#c8963e);
  border:1px solid var(--color-command-gold,#c8963e);border-radius:2px;padding:0 .22rem;}
.gs-lw{--spread:9px;} .gs-ln{--spread:5px;}

/* Reflow off the FRAME width, never the viewport, so a diagram in the narrow
   follower rail gets the phone form too. */
@container (max-width:520px){
  .gs-wide{display:none;}
  .gs-narrow{display:block;}
  .gs-label em{display:none;}
}

@media (prefers-reduced-motion:reduce){
  .gs-sheet,.gs-label{transform:none!important;}
  .gs-sheet{opacity:var(--base)!important;}
}
`;
