allowBuilds:
  '@prisma/engines': true
  core-js: false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  '@hono/node-server@<1.19.13': ^1.19.13
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  hono@<4.12.25: ^4.12.25
  postcss@<8.5.10: ^8.5.10
