// SANDBOX - the kit choice, made against the picture instead of in the dark.
// DEV ONLY.
//
// The five beds render to C:/zzz/_hex-promo/kits/logbook-bed-*.wav. To audition
// them here, copy them into the gitignored capture directory - they are 960 KB
// each and this repo is public:
//
//   New-Item -ItemType Directory -Force public\_capture\logbook-beds
//   foreach ($k in "relay","forge","machine","quiet","plate") {
//     Copy-Item "C:\zzz\_hex-promo\kits\logbook-bed-$k.wav" "public\_capture\logbook-beds\$k.wav"
//   }
//
// ASCII only.

import { Suspense } from "react";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { db } from "@/lib/db";
import { parseGuideBlocks } from "@/lib/guide-blocks-parse";
import type { FilmLesson, FilmQuestion } from "../LogbookLive";
import { BedRig, type BedKit } from "./BedRig";

/** The five, with the claim each one makes. Copied from the KITS table in
 *  tools/logbook-bed.py, which is where they are defined. */
const KITS: BedKit[] = [
  {
    id: "relay",
    title: "Relay",
    group: "one arrangement, five palettes · the KIT axis",
    note: "Electrical. Relays and clank, an arc into every landing - the kit that speaks the quiz's own language, where an answer is a circuit closing.",
  },
  {
    id: "forge",
    title: "Forge",
    note: "Struck and warm. Taiko and impact carry it, a rim for the answer, the wheel ticked out on a rim as well so bar four stays dry.",
  },
  {
    id: "machine",
    title: "Machine",
    note: "Servos and shakers. The wheel is the loudest idea in the kit, which suits a film whose third beat is a mechanism and risks making the dip the thing you remember.",
  },
  {
    id: "quiet",
    title: "Quiet",
    note: "Sparse. Nothing between the landings, so the four events and the two between them are the whole arrangement.",
  },
  {
    id: "plate",
    title: "Plate",
    note: "PICKED (owner, 2026-08-12), for its pacing. Built around the LAST event rather than the biggest one: the 8.0 drop is pulled back and the 8.5 plating gets a real swell, so the film resolves on the badge becoming yours instead of on it arriving.",
  },
  {
    id: "plate-master",
    title: "Plate / master",
    // THE POINT OF AUDITIONING THE MASTER HERE. The finishing chain is where an
    // arrangement gets quietly levelled - convolution, glue compression and a
    // limiter all trade dynamics for loudness, and loudnorm's `linear=true` is a
    // request rather than a guarantee. Measured, this one held: the six peaks
    // moved by at most 0.009 relative to PATCH and crest fell 0.56 dB. Left on
    // the page anyway, because the next kit or the next chain change is exactly
    // when that stops being true, and the A/B is one click.
    note: "The same kit through tools/hex-master.py: church-IR convolution, gentle glue, true-peak limit, -14.25 LUFS (linear, capped 0.25 dB short of -14 rather than falling back to dynamic). A/B it against the raw plate above.",
  },
  {
    id: "plate-soft",
    title: "Plate / soft",
    note: "Plate with the soft-clip drive at 0.6 instead of 1.1. Same arrangement, same samples - this is the curve the arrangement WROTE, rather than a compressed version of it: rms error against 0.55/0.78/0.70/1.00 falls 0.073 to 0.030, crest rises 13.7 to 15.8 dB.",
  },
  {
    id: "plate-soft-master",
    title: "Plate / soft, master",
    // THE DECISION THIS PAGE NOW EXISTS TO SETTLE. Two mastered candidates that
    // differ by one number in the generator, and the trade is not free: the
    // honest curve is 1.9 dB quieter in a feed, and platforms only ever turn
    // material DOWN, so nothing gives that back. Numbers cannot answer it -
    // 2 dB of level against 2 dB of crest is a listening call.
    note: "The honest curve, mastered: -16.16 LUFS (linear, 2.16 dB short of -14) against plate's -14.25. THE TRADE: the authored weight curve and 2 dB more crest, for 1.9 dB less loudness in the feed. Nothing turns that back up. A/B against plate / master.",
  },

  // THE SECOND AXIS, AND THE REASON PLATE WAS ONLY "OKAY". Everything above is
  // ONE arrangement in five costumes - same landings, same wheel, same layered
  // drop, same sub. Exhausting that axis is what "just okay" sounds like.
  // Below, the palette is HELD FIXED at plate's samples and the WRITING varies,
  // so any difference you hear is composition rather than sample choice.
  // Generated by tools/logbook-comp.py; every one is measured against the same
  // weight curve on render, because the picture is built to that curve whatever
  // the music does.
  {
    id: "comp-strike",
    title: "Strike",
    group: "ten arrangements, one palette · the COMPOSITION axis",
    note: "The control. The arrangement we already have, at the honest drive, so every composition below is judged against it rather than against a memory. Percussion only - no tonal content beyond the sub.",
  },
  {
    id: "comp-ladder",
    title: "Ladder",
    note: "PITCH IS RANK. Each landing steps up the mode and the wheel at 6.0 runs the ladder rather than ticking. Ends a seventh above where it started, so the loop drops back to bar one - the climb resets, which is what a rank ladder does to everyone who finishes it. The film's own idea, as music.",
  },
  {
    id: "comp-converge",
    title: "Converge",
    note: "The Deep Note move. A wide detuned cluster wanders for eight seconds and locks into a chord exactly on the plating; the landings are marked by the cluster TIGHTENING. The only one whose payoff is focus rather than impact - and the nearest thing to prior art an engineering brand has.",
  },
  {
    id: "comp-sequence",
    title: "Sequence",
    note: "An instrument idling. Sixteenths run the whole clip like a machine that was already on before the film started, and the landings are harmonic changes inside the figure rather than events on top of it. Closest to the console/telemetry read, and the one that would survive being cut to a different length.",
  },
  {
    id: "comp-fanfare",
    title: "Fanfare",
    note: "Ceremonial. Stacked stabs, a real cadence into 8.0, the plating as resolution. Sounds like something is being awarded - which is either exactly right for a badge film or exactly the generic thing a gamification promo does. Worth hearing before ruling out.",
  },
  {
    id: "comp-pulse",
    title: "Pulse",
    note: "Austere. One pulse a bar and almost nothing else, so the silence between the landings is the arrangement. The bed that AGREES with a film showing one subject per beat instead of filling in around it.",
  },
  {
    id: "comp-drone",
    title: "Drone",
    note: "Escalate by COLOUR, not volume - the instruction the weight curve already carries, applied to the whole piece. One sustained pad whose harmony changes on each landing: open fifth, add the third, darken, resolve. Nothing in it gets louder on purpose.",
  },
  {
    id: "comp-motif",
    title: "Motif",
    note: "Four notes: stated at 2.0, answered at 4.0, inverted at 6.0, resolved at 8.0. THE ONLY ONE BUILT TO BE SHORTENED - a 3s stinger or a 1s ping is the same four notes, which is how every tiered sonic-brand system works. If we ever want an audio logo, it starts here.",
  },
  {
    id: "comp-mechanism",
    title: "Mechanism",
    note: "No tonal centre at all. The wheel's idea - spacing as meaning - extended over the whole piece: relays and ticks escalating by DENSITY, and the third bar thinning to make the dip. The one that could not be mistaken for another brand's bed.",
  },
  {
    id: "comp-duet",
    title: "Duet",
    note: "Call and response. Percussion states, a pitched voice replies half a beat later, which makes the quiz's one click at 1.5 the grammatical subject of the whole piece. The cost is that little lands cleanly on a downbeat except the answer - that is either the idea or the problem.",
  },

  // ROUND TWO. Owner kept duet, motif and sequence, and asked for more bass,
  // gravity and seriousness - a defense company. "More serious" is not a note
  // you can act on; four specific things are, and all eight below change all
  // four: register (an octave to a twelfth lower), mode (aeolian - dorian's
  // raised sixth is what keeps a piece from reading sad, and "not sad" is not
  // "grave"), harmony (open fifths, which decline to be major or minor), and
  // bass that is PLAYED and saturated so its harmonics land in the 250-700 Hz
  // band a phone can actually reproduce.
  {
    id: "comp-keel",
    title: "Keel",
    group: "the serious set · defense register · round two · READ THE CHECK CAVEAT",
    note: "SEQUENCE taken down. The idling machine an octave lower, eighths instead of sixteenths, on open fifths. What was a console ticking over becomes something with a displacement - a figure you feel rather than follow. CHECK CAVEAT: flags 'learn < gain' here, but that is the bass floor being measured, not the writing - with the bass removed it is 0.619 / 0.831 / 0.776, curve error 0.058.",
  },
  {
    id: "comp-grave",
    title: "Grave",
    note: "MOTIF taken down and slowed. The four notes on whole beats instead of half beats, an octave lower, every one doubled by the bass. Slow is the other half of serious: the round-one motif moved at the speed of a jingle because it was written as one.",
  },
  {
    id: "comp-sentry",
    title: "Sentry",
    note: "DUET taken down. The answer comes back BELOW the call instead of above it, so the reply is heavier than the question. That inversion is most of why it reads as authority rather than as conversation. CHECK CAVEAT: the heavier-reply idea is itself what trips 'learn < gain' - a low reply under the first landing IS louder than the second landing. Over the bass floor, 0.615 / 0.650 / 0.590. The flattest climb of the set, by construction.",
  },
  {
    id: "comp-brief",
    title: "Brief",
    note: "MOTIF x DUET. The percussion asks on every downbeat and the mnemonic is the ANSWER, half a beat later, every time - four statements of one figure in four harmonic positions. The combination with the most to gain, and the one that cuts down cleanest: the reply plus its call is a three-second stinger.",
  },
  {
    id: "comp-watch",
    title: "Watch",
    note: "SEQUENCE x DUET. The machine idles the whole way through and STOPS for half a beat at each landing; something answers into the hole it leaves. The call is the silence. A running figure cannot make room by getting louder - it makes room by stopping. CHECK CAVEAT: flags on the summed audio; over the bass floor it is 0.611 / 0.810 / 0.760, curve error 0.046 - one of the cleanest arrangements in the set.",
  },
  {
    id: "comp-standard",
    title: "Standard",
    note: "MOTIF x SEQUENCE. The figure is not laid over the machine, it IS the machine's top line - picked out louder at each landing. One texture, two readings. The claim: a mnemonic buried in working material convinces more than one announced over it, which is the difference between a signature and a slogan.",
  },
  {
    id: "comp-hull",
    title: "Hull",
    note: "ALL THREE at weight. Sequence idles and stops, motif answers into the stop, bass plays the motif's root underneath. The honest risk of any combination is three ideas competing instead of one idea with three parts - this is the one to listen hardest for that. CHECK CAVEAT: flags 'dip missing' on the summed audio, but over the bass floor it measures 0.587 / 0.795 / 0.739 for a curve error of 0.028 - the tightest ARRANGEMENT of all eighteen. Whether that survives the bass is the listening question.",
  },
  {
    id: "comp-anchor",
    title: "Anchor",
    note: "THE LIMIT CASE. One low pedal for the full ten seconds, three fragments of the motif, almost no percussion, and the third landing's dip is a SILENCE rather than a smaller sound. If this is too little it tells you how much of the others is load-bearing; if it is not, it tells you the rest are overwritten.",
  },

  // ROUND THREE AND FOUR: THE MODE SWEEP.
  //
  // "The serious set is cool, but ominous." Ominous is a MODE problem, and the
  // obvious other answer is a dead end worth recording. Powell & Dibben (2005):
  // on an equal-tempered instrument listeners cannot identify mood from key or
  // key from mood, and transposing does not change perceived mood. Historical
  // key characters were real and were artifacts of UNEQUAL temperaments; ET
  // removes the mechanism. Every oscillator here is ET, so A to C to F# changes
  // register and nothing else.
  //
  // Mode does the work and it has an ORDER. Temperley & Tan, Music Perception
  // 30(3): the same melodies in six modes over a fixed tonic, judged pairwise
  // for which is happier, come out in line-of-fifths order - Ionian, Mixolydian,
  // Dorian, Aeolian, Phrygian, happiest to saddest. Round two is in AEOLIAN,
  // second-saddest of the six. Not a subtle mis-set.
  //
  // Mode is the ONLY variable below: same register, timbre, bass, percussion,
  // written once and run through one wrapper. One caveat is load-bearing - in a
  // bright mode the sequence figure re-admits the THIRD, because open fifths
  // refuse to declare a mode and relabelling the scale under a fifths-only
  // arrangement would have been inaudible.
  //
  // The two sweep groups run happiest-first and omit AEOLIAN, which is the
  // serious set above - listing it twice would be two entries pointing at one
  // render. Locrian is absent for a different reason: its fifth is diminished,
  // and this music is voiced on open fifths, so it has no stable fifth to voice
  // on. Not a mood option, a broken one.
  {
    id: "comp-hull-ion",
    title: "Hull / ionian",
    group: "sweep · HULL, happiest first (aeolian = Hull, above)",
    note: "Straight major. The top of the ordering, here so it is audible rather than assumed - almost certainly too pleased with itself for a defense brand, but you cannot know where the middle is without hearing both ends.",
  },
  {
    id: "comp-hull-lyd",
    title: "Hull / lydian",
    note: "The raised fourth: altitude and wonder rather than confidence. Rated LESS happy than ionian despite sitting higher up the line of fifths, which is the one place the ordering breaks. The closest this set gets to aspirational without going saccharine.",
  },
  {
    id: "comp-hull-mixo",
    title: "Hull / mixolydian",
    note: "Major third and sixth restored, only the seventh lowered - the mode film scoring reaches for when it wants confident and heroic without the saccharine of straight major. The mode change also cleaned its measurement: 0.092 and flagging in aeolian, 0.040 and clean here, because admitting the third changes which partials peak in the landing windows.",
  },
  {
    id: "comp-hull-dor",
    title: "Hull / dorian",
    note: "One step darker than mixolydian: minor third kept, major sixth restored. Curve error 0.024 over the bass floor - the tightest arrangement anywhere in this rig. The summed 'dip missing' flag is the bass floor again, not the writing.",
  },
  {
    id: "comp-hull-phr",
    title: "Hull / phrygian",
    note: "The flat SECOND. Saddest of the six and frankly menacing - the bottom of the range, for calibration. If aeolian read ominous, this is what ominous actually is.",
  },
  {
    id: "comp-standard-ion",
    title: "Standard / ionian",
    group: "sweep · STANDARD, happiest first (aeolian = Standard, above)",
    note: "Straight major on the signature-buried-in-working-material arrangement.",
  },
  {
    id: "comp-standard-lyd",
    title: "Standard / lydian",
    note: "Raised fourth - wonder and altitude on a figure that is otherwise all business.",
  },
  {
    id: "comp-standard-mixo",
    title: "Standard / mixolydian",
    note: "Two steps up the ordering from round two with none of the weight given back. If one mode is the answer to “serious, professional, but fun”, the ordering says it is this one.",
  },
  {
    id: "comp-standard-dor",
    title: "Standard / dorian",
    note: "THE HALFWAY HOUSE. Minor third kept, major sixth restored: one step up from aeolian rather than two. Where round one already was, now carrying round two's weight - and if mixolydian reads too pleased with itself, this is where serious-with-a-shade-of-hope actually lives.",
  },
  {
    id: "comp-standard-phr",
    title: "Standard / phrygian",
    note: "The bottom of the range, for calibration.",
  },
  {
    id: "comp-grave-mixo",
    title: "Grave / mixo",
    group: "mixolydian for the rest of the serious set",
    note: "GRAVE in mixolydian, which makes the name a lie and that is rather the point: the same slow low four notes, no longer funereal. Curve error 0.027 over the bass floor.",
  },
  {
    id: "comp-brief-mixo",
    title: "Brief / mixo",
    note: "The mnemonic answering on every downbeat, in the mode that reads as capable rather than as a threat. Still the candidate that cuts down cleanest to a stinger.",
  },
  {
    id: "comp-brief-dor",
    title: "Brief / dorian",
    note: "The stinger candidate at the halfway house. If one of these becomes the thing you hear on every lesson completion, it is most likely this one - dorian survives repetition better than either end of the range.",
  },
  {
    id: "comp-keel-mixo",
    title: "Keel / mixo",
    note: "The idling machine with a third in it, so the figure finally has a mode at all rather than bare fifths - and the flag it carried in aeolian is gone.",
  },
  {
    id: "comp-sentry-mixo",
    title: "Sentry / mixo",
    note: "The heavier-than-the-call reply without the gloom that made it read as a warning. Still carries its climb flag, and that flag IS the idea: a reply pitched below its call is louder than the landing after it.",
  },
  {
    id: "comp-watch-mixo",
    title: "Watch / mixo",
    note: "The machine stops for half a beat and something confident answers into the hole. 0.041 over the bass floor.",
  },
  {
    id: "comp-anchor-mixo",
    title: "Anchor / mixo",
    note: "The limit case, lit: one pedal and three fragments, no longer a dirge. WORTH KNOWING: anchor originally used only root, fifth and octave - intervals that are identical in every diatonic mode - so its first mixolydian render came back byte-identical to the aeolian one. Its fragments now include the THIRD, which is the note that carries mode at all.",
  },
];

export default function BedCutPage() {
  if (process.env.NODE_ENV === "production") notFound();
  return (
    <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
      <p className="font-mono text-[10px] uppercase tracking-[0.24em] text-command-gold">
        &#9656; THE LOGBOOK &middot; bed against picture
      </p>
      <h1 className="title-section mt-3">Which kit, and does it hit</h1>

      <p className="mt-4 max-w-3xl font-serif text-base text-text">
        The cut is locked and the bed is not. Five kits, one picture, one clock:
        the film&rsquo;s scene time is read off the audio, so what you are
        watching is not a preview running alongside a track, it is the track
        driving the frame. Swap kits while it runs and the picture does not
        restart &mdash; the same moment, two beds, one after the other.
      </p>

      <section className="mt-5 border-y border-panel-border/60 py-4">
        <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-command-gold">
          &#9656; how to judge a miss
        </p>
        <ul className="mt-2 max-w-3xl space-y-1 font-serif text-sm text-muted">
          <li>
            <b className="text-title">The word is meant to be early.</b> Three
            frames, 0.1s, whole-cut. A word landing exactly on the downbeat is
            measurably correct and reads late. The waveform marks both: gold
            where the bed hits, dashed blue where the word should settle.
          </li>
          <li>
            <b className="text-title">Null your own latency first.</b> What you
            hear left the audio graph tens of milliseconds ago; what you see is
            on screen now. The nudge starts at minus the measured output latency
            &mdash; if the grid clicks feel late against the bed, that is the
            control to move, not the cut.
          </li>
          <li>
            <b className="text-title">Grid clicks are the ear&rsquo;s marker
            lines.</b> A blip on each of the six events, sample-accurate. A bed
            that sounds early against them is early.
          </li>
          <li>
            <b className="text-title">On the serious set, the check measures
            the bass.</b> Peak-in-a-window assumes the landing IS the peak, which
            it is in a percussion bed and is not once a sustained saturated low
            end raises the floor in every window. Four of round two flag on the
            summed audio and measure clean with the bass removed &mdash; those
            carry the dry numbers in their note. Trust the flag on rounds one
            and two&rsquo;s percussion pieces; read the caveat on the bass-forward ones.
          </li>
          <li>
            <b className="text-title">The curve is checked, not eyeballed.</b>{" "}
            0.55 / 0.78 / <b>0.70</b> / 1.00 &mdash; the dip at the third is
            deliberate. Every kit&rsquo;s six peaks are re-measured in the
            browser from the decoded buffer, the same 0.25s window{" "}
            <code className="font-mono text-[13px] text-gold-light">
              landing_peaks()
            </code>{" "}
            uses, and stated as pass/fail.
          </li>
        </ul>
      </section>

      <Suspense
        fallback={<p className="mt-8 font-mono text-xs text-muted">loading&hellip;</p>}
      >
        <Body />
      </Suspense>
    </main>
  );
}

/** The same question the assembly page films, found the same way: the shortest
 *  real quiz question in a published Fundamentals mini-lesson. Kept local
 *  rather than shared, because this route is deleted with the rest of the
 *  sandbox and nothing outside it should grow a dependency on the query. */
async function findQuestion() {
  const rows = await db.miniLesson.findMany({
    where: { published: true, accessTier: "PUBLIC", cluster: "fundamentals" },
    orderBy: { clusterOrdinal: "asc" },
    select: { slug: true, title: true, contentBlocks: true },
    take: 12,
  });
  let lesson: FilmLesson | null = null;
  let question: FilmQuestion | null = null;
  for (const r of rows) {
    const qs = parseGuideBlocks(r.contentBlocks)
      .blocks.filter((b) => b.type === "quiz")
      .flatMap((b) => (b.type === "quiz" ? b.questions : []))
      .filter(
        (q): q is FilmQuestion =>
          Array.isArray(q.options) && q.options.length >= 2 && typeof q.answer === "number",
      );
    for (const q of qs) {
      const worse =
        question &&
        q.options.length * 100 + q.q.length >=
          question.options.length * 100 + question.q.length;
      if (worse) continue;
      question = q;
      lesson = { slug: r.slug, title: r.title, clusterLabel: "Fundamentals" };
    }
  }
  return lesson && question ? { lesson, question } : null;
}

async function Body() {
  // The sibling assembly page gets away without this because it awaits
  // `searchParams` first, which is Request data. This one reads no params and
  // no session, so nothing else establishes that it runs at request time - and
  // under cacheComponents the Prisma client's internal clock read then trips
  // the "current time before any Request data" prerender error. Same fix the
  // curriculum page carries, same reason.
  await connection();
  const found = await findQuestion();
  if (!found) {
    return (
      <p className="mt-6 border border-danger-coral/40 bg-danger-coral/5 p-3 font-mono text-xs text-danger-coral">
        No published Fundamentals lesson in the local database carries a parseable
        quiz block. Hydrate with <code>pnpm db:pull-prod</code>.
      </p>
    );
  }
  return (
    <div className="mt-8">
      <BedRig kits={KITS} lesson={found.lesson} question={found.question} />
    </div>
  );
}
