import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

import {
  collectNotices,
  renderNotices,
  MIN_PACKAGES,
  COPYLEFT_ALLOW,
  copyleftViolations,
  isCopyleft,
} from "../../scripts/gen-third-party-notices";

// /THIRD_PARTY_NOTICES.txt is generated on every `pnpm build` and gitignored, so
// there is no committed file for CI to look at. This is the CI check instead: it
// runs the same walk the build runs, against the installed tree, and fails if
// the result would be missing or hollow -- and it fails if the build script
// stops running the generator, which is the other way the file goes missing.

const ROOT = process.cwd();
const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};
const entries = collectNotices(ROOT);
const byName = new Map(entries.map((e) => [e.name, e]));

describe("third-party notices", () => {
  it("is generated by the build script, before next build", () => {
    const build = pkg.scripts.build;
    const gen = build.indexOf("scripts/gen-third-party-notices.ts");
    expect(gen, build).toBeGreaterThanOrEqual(0);
    expect(gen).toBeLessThan(build.indexOf("next build"));
  });

  it("finds a plausible number of production packages", () => {
    expect(entries.length).toBeGreaterThanOrEqual(MIN_PACKAGES);
  });

  it("lists every direct production dependency", () => {
    for (const dep of Object.keys(pkg.dependencies)) {
      expect(byName.has(dep), dep).toBe(true);
    }
  });

  it("leaves out dev-only dependencies", () => {
    // vitest is dev-only and nothing in production depends on it.
    expect(byName.has("vitest")).toBe(false);
  });

  it("carries licence text for the frameworks the site is built on", () => {
    for (const name of ["next", "react", "react-dom"]) {
      const e = byName.get(name);
      expect(e?.license, name).toBe("MIT");
      expect(e?.texts.length, name).toBeGreaterThan(0);
    }
  });

  it("ships no copyleft-licensed production dependency", () => {
    // The real tree. Before the c15t 2.2.1 upgrade this was red:
    // @c15t/translations@2.0.0-rc.8 declared GPL-3.0-only.
    //
    // RED ON PURPOSE when this guard landed (2026-09-25), on three packages
    // that predate it and each need an owner decision -- replace, or an
    // allow-list entry with a written reason:
    //   jszip@3.10.1              (MIT OR GPL-3.0-or-later)  dual; MIT side is takeable
    //   occt-import-js@0.0.23     LGPL-2.1                   wasm served to the client
    //   @img/sharp-*/libvips      LGPL-3.0-or-later          next's server-side sharp
    // Do not make this green by weakening the match.
    const bad = copyleftViolations(entries).map((e) => `${e.name}@${e.version} (${e.license})`);
    expect(bad).toEqual([]);
  });

  it("keeps the copyleft allow-list empty", () => {
    // Adding an entry is an owner decision, not a way to turn this suite green.
    expect(COPYLEFT_ALLOW).toEqual([]);
  });

  it("recognises every copyleft spelling, and nothing permissive", () => {
    const copyleft = [
      "GPL-3.0-only",
      "gpl-2.0-or-later",
      "GPL-2.0+",
      "GPLv3",
      "LGPL-2.1-only",
      "LGPL-3.0-or-later",
      "AGPL-3.0-only",
      "agpl-3.0",
      "SSPL-1.0",
      "(MIT OR GPL-3.0-or-later)",
      "Apache-2.0 AND LGPL-3.0-only",
      "GPL-2.0-only WITH Classpath-exception-2.0",
      "GNU General Public License v3",
      "GNU Affero General Public License",
      "Server Side Public License",
    ];
    const permissive = [
      "MIT",
      "Apache-2.0",
      "BSD-3-Clause",
      "ISC",
      "MPL-2.0",
      "0BSD",
      "BlueOak-1.0.0",
      "CC-BY-4.0",
      "(MIT OR Apache-2.0)",
      "Python-2.0",
      "UNKNOWN",
    ];
    for (const l of copyleft) expect(isCopyleft(l), l).toBe(true);
    for (const l of permissive) expect(isCopyleft(l), l).toBe(false);
  });

  it("flags a GPL entry in the real tree, and only an exact name+version allow-list entry clears it", () => {
    // Fixture: the real closure with one Apache package relabelled as the rc it
    // replaced. Proves the guard reads the tree it is given, not a constant.
    const target = entries.find((e) => e.name === "@c15t/translations")!;
    expect(target.license).toBe("Apache-2.0");
    const poisoned = entries.map((e) => (e === target ? { ...e, license: "GPL-3.0-only" } : e));
    // Compared against the unpoisoned baseline, so this test is about the
    // mechanism and stays independent of whatever the real tree holds.
    const baseline = new Set(copyleftViolations(entries).map((e) => e.name));
    const added = (allow?: { name: string; version: string }[]) =>
      copyleftViolations(poisoned, allow)
        .map((e) => e.name)
        .filter((n) => !baseline.has(n));
    expect(added()).toEqual(["@c15t/translations"]);
    expect(added([{ name: target.name, version: "0.0.0-other" }])).toEqual(["@c15t/translations"]);
    expect(added([{ name: target.name, version: target.version }])).toEqual([]);
  });

  it("renders a non-empty text file naming each package and its licence", () => {
    const txt = renderNotices(entries);
    expect(txt.length).toBeGreaterThan(10_000);
    expect(txt).toContain(`Packages: ${entries.length}`);
    const next = byName.get("next")!;
    expect(txt).toContain(`${next.name} ${next.version}\nLicense: MIT`);
  });
});
