import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

import {
  collectNotices,
  renderNotices,
  MIN_PACKAGES,
} from "../../scripts/gen-third-party-notices";

// /THIRD_PARTY_NOTICES.txt is generated on every `pnpm build` and gitignored, so
// there is no committed file for CI to look at. This is the CI check instead: it
// runs the same walk the build runs, against the installed tree, and fails if
// the result would be missing or hollow -- and it fails if the build script
// stops running the generator, which is the other way the file goes missing.

const ROOT = process.cwd();
const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};
const entries = collectNotices(ROOT);
const byName = new Map(entries.map((e) => [e.name, e]));

describe("third-party notices", () => {
  it("is generated by the build script, before next build", () => {
    const build = pkg.scripts.build;
    const gen = build.indexOf("scripts/gen-third-party-notices.ts");
    expect(gen, build).toBeGreaterThanOrEqual(0);
    expect(gen).toBeLessThan(build.indexOf("next build"));
  });

  it("finds a plausible number of production packages", () => {
    expect(entries.length).toBeGreaterThanOrEqual(MIN_PACKAGES);
  });

  it("lists every direct production dependency", () => {
    for (const dep of Object.keys(pkg.dependencies)) {
      expect(byName.has(dep), dep).toBe(true);
    }
  });

  it("leaves out dev-only dependencies", () => {
    // vitest is dev-only and nothing in production depends on it.
    expect(byName.has("vitest")).toBe(false);
  });

  it("carries licence text for the frameworks the site is built on", () => {
    for (const name of ["next", "react", "react-dom"]) {
      const e = byName.get(name);
      expect(e?.license, name).toBe("MIT");
      expect(e?.texts.length, name).toBeGreaterThan(0);
    }
  });

  it("renders a non-empty text file naming each package and its licence", () => {
    const txt = renderNotices(entries);
    expect(txt.length).toBeGreaterThan(10_000);
    expect(txt).toContain(`Packages: ${entries.length}`);
    const next = byName.get("next")!;
    expect(txt).toContain(`${next.name} ${next.version}\nLicense: MIT`);
  });
});
