// Build-time generator: the L1.01 answer-key Gerber set -> a committed data module
// the L101GerberStack diagram imports.
//
// The .gbr files themselves are the owner's verified answer key and live outside
// the repo (they ship to learners as the GERBER_ZIP artifact on the published
// revision, not as source). Point --src at that folder and re-run to regenerate.
//
//   pnpm tsx scripts/gen-l101-gerber-data.ts --src "C:/.../l1-01-wroom-breakout/gerbers"
//
// Nothing at runtime parses Gerber; the diagram imports only the emitted paths.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { parseGerber, simplifyPath, type GerberPath } from "./gerber-to-paths";

const DEFAULT_SRC =
  "C:/Users/raven/Downloads/l1-01-wroom-breakout-v1-starter-key/l1-01-wroom-breakout/gerbers";
const STEM = "l1-01-wroom-breakout";
const OUT = "src/components/guide/diagrams/data/l101-gerber-layers.ts";

// Front to back, the order the sheets are pressed together.
const SHEETS = [
  { id: "fs", file: "F_Silkscreen", name: "F_Silk", kind: "silk", gloss: "the labels", eps: 0.15 },
  { id: "fm", file: "F_Mask", name: "F_Mask", kind: "mask", gloss: "openings at the pads", eps: 0.05 },
  { id: "fc", file: "F_Cu", name: "F_Cu", kind: "cu", tag: "L1", gloss: "your traces", eps: 0.05 },
  { id: "i1", file: "In1_Cu", name: "In1_Cu", kind: "cu", tag: "L2", gloss: "ground plane", eps: 0.05 },
  { id: "i2", file: "In2_Cu", name: "In2_Cu", kind: "cu", tag: "L3", gloss: "ground plane", eps: 0.05 },
  { id: "bc", file: "B_Cu", name: "B_Cu", kind: "cu", tag: "L4", gloss: "back-side traces", eps: 0.05 },
  { id: "bm", file: "B_Mask", name: "B_Mask", kind: "mask", gloss: "openings at the pads", eps: 0.05 },
  { id: "bs", file: "B_Silkscreen", name: "B_Silk", kind: "silk", gloss: "the labels", eps: 0.15 },
] as const;

function main() {
  const argSrc = process.argv.indexOf("--src");
  const src = argSrc > -1 ? process.argv[argSrc + 1] : DEFAULT_SRC;
  const at = (layer: string) => `${src}/${STEM}-${layer}.gbr`;
  if (!existsSync(at("Edge_Cuts"))) {
    console.error(`No Gerber set at ${src}\nPass --src <folder> pointing at the answer-key gerbers.`);
    process.exit(1);
  }

  // Edge_Cuts defines the board frame. Its bbox is the origin every sheet is
  // re-based to, and it doubles as the clip path and the drawn outline.
  const edge = parseGerber(readFileSync(at("Edge_Cuts"), "utf8"));
  const [OX, OY] = edge.bbox;
  const outline = simplifyPath(edge.paths[0].d, 0.02, OX, OY);

  const emitted: string[] = [];
  let bytes = 0;
  for (const s of SHEETS) {
    const g = parseGerber(readFileSync(at(s.file), "utf8"));
    const paths: GerberPath[] = g.paths
      .slice()
      // the poured region is the background of its own sheet, so it draws first
      .sort((a, b) => (b.region ? 1 : 0) - (a.region ? 1 : 0))
      .map((p) => ({ ...p, d: simplifyPath(p.d, s.eps, OX, OY) }));
    bytes += paths.reduce((a, p) => a + p.d.length, 0);
    emitted.push(
      `  {\n` +
        `    id: ${JSON.stringify(s.id)},\n` +
        `    name: ${JSON.stringify(s.name)},\n` +
        `    file: ${JSON.stringify(`${STEM}-${s.file}.gbr`)},\n` +
        `    kind: ${JSON.stringify(s.kind)},\n` +
        ("tag" in s ? `    tag: ${JSON.stringify(s.tag)},\n` : "") +
        `    gloss: ${JSON.stringify(s.gloss)},\n` +
        `    fileFunction: ${JSON.stringify(g.meta.FileFunction ?? "")},\n` +
        `    polarity: ${JSON.stringify(g.meta.FilePolarity ?? "")},\n` +
        `    flashes: ${g.flashCount},\n` +
        `    regions: ${g.regionCount},\n` +
        `    paths: [\n` +
        paths
          .map(
            (p) =>
              `      { kind: ${JSON.stringify(p.kind)}${p.width != null ? `, width: ${p.width}` : ""}` +
              `${p.region ? ", region: true" : ""}, d: ${JSON.stringify(p.d)} },`,
          )
          .join("\n") +
        `\n    ],\n  },`,
    );
    console.log(
      `${s.name.padEnd(10)} ${(g.meta.FileFunction ?? "?").padEnd(16)} ${(g.meta.FilePolarity ?? "?").padEnd(9)} ` +
        `flashes ${String(g.flashCount).padStart(3)}  regions ${String(g.regionCount).padStart(2)}`,
    );
  }

  const out = `// GENERATED by scripts/gen-l101-gerber-data.ts -- do not edit by hand.
//
// The real L1.01 answer-key Gerber set, parsed from the .gbr files and re-based to
// the Edge_Cuts origin. Every path here is geometry the board house would build
// from; nothing is drawn by hand. Coordinates are millimetres, Y down.
//
// Simplified to each sheet's own tolerance (0.05 mm on copper and mask, 0.15 mm on
// the silkscreen text) which is well under a pixel at the size a stacked sheet
// renders. Regenerate with:
//   pnpm tsx scripts/gen-l101-gerber-data.ts --src <answer-key gerbers folder>

export interface GerberSheetPath {
  kind: "fill" | "stroke";
  width?: number;
  region?: boolean;
  d: string;
}

export interface GerberSheet {
  id: string;
  name: string;
  file: string;
  kind: "cu" | "mask" | "silk";
  tag?: string;
  gloss: string;
  /** the X2 FileFunction attribute, verbatim: this is what fixes the stack order */
  fileFunction: string;
  polarity: string;
  flashes: number;
  regions: number;
  paths: GerberSheetPath[];
}

/** Board outline from Edge_Cuts, at the origin. Doubles as the sheet clip path. */
export const BOARD = {
  w: ${edge.w},
  h: ${edge.h},
  outline: ${JSON.stringify(outline)},
} as const;

/** Front to back, the order the sheets are pressed together. */
export const SHEETS: GerberSheet[] = [
${emitted.join("\n")}
];
`;
  writeFileSync(OUT, out);
  console.log(`\nwrote ${OUT}  (${(out.length / 1024).toFixed(0)} KB, geometry ${(bytes / 1024).toFixed(0)} KB)`);
  console.log(`board ${edge.w} x ${edge.h} mm from Edge_Cuts`);
}

main();
