// Package + upload the hex-cluster printables to R2.
//
//   pnpm tsx scripts/upload-printables.ts --allow-list <file>           # DRY RUN
//   pnpm tsx scripts/upload-printables.ts --allow-list <file> --write   # uploads
//
// The allow-list (or PRINTABLES_ALLOWLIST) is REQUIRED: it names every source
// file that may be published and the licence each ships under. Only `cc-by`
// passes; a `third-party` row, a row with no licence, a file the manifest has but
// the list does not, or a listed file the manifest lacks each refuse the whole
// run before anything is written. A manifest part the list names under
// `withheld` (with its reason) is SKIPPED and logged, never uploaded; that is
// the only way a manifest part may be left out. Format:
// scripts/lib/printables-allowlist.ts.
//
// `--write` also refuses while any `[OWNER-WORDING: ...]` placeholder remains in
// any file it would upload (the LICENSE disclaimer of 6.8, the README safety
// text of 2.6, or any later one). A dry run emits them, so they can be read.
//
// Every PUT carries `x-amz-meta-sha256` (hex SHA-256 of the bytes) and
// `Content-Disposition: attachment`. Before writing, every key is HEADed:
//   absent (404)                 -> uploaded
//   present, same sha256         -> skipped (this is what makes a rerun resume)
//   present, other/absent sha256 -> REFUSED, nothing is written
//   any other HEAD error         -> FATAL, nothing is written
// There is no `--force`. A published key is immutable; replacing its bytes is a
// new release segment, never an overwrite.
//
// PRINTABLES_EMIT=<dir> makes a dry run WRITE the bytes it would upload, so the
// zip and its README can be opened before anything is published. Worth doing:
// the keys are immutable, so a wrong README costs a new release segment.
//
// Reads the mesh set generated by the PRIVATE hardware repo
// (`otd-dev-hardware/enclosure/tools/build_printables.py`) and pushes it to R2
// under an immutable `printables/{release}/...` prefix. The .FCStd sources stay
// private; only generated meshes ship.
//
// !! THERE IS NO LOCAL R2. !!
// Unlike the database — where `.env.local` points at local Postgres since
// 2026-07-15, so scripts are safe by default — R2_* credentials in `.env.local`
// are the REAL bucket. `--write` therefore uploads to production storage. Hence
// dry run is the default and prints every object it would put, matching the
// convention in scripts/import-content.ts.
//
// Set membership below is a PROPOSAL pending the owner's call on what is free
// vs gated. Edit SETS, not the upload logic.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import JSZip from "jszip";
import { createHash } from "node:crypto";
import { HeadObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import {
  checkAgainstAllowList,
  isManifestPath,
  loadAllowList,
} from "./lib/printables-allowlist";

// The print spec, shared with the academy's /hex page. A plain data module with
// no env dependency, so a static import is safe above the dotenv call below.
import {
  HEX_CLEARANCE,
  HEX_ORIENTATION,
  HEX_PRINT_PARAMS,
  HEX_RELEASE,
} from "../src/lib/hex-spec";
// Plain data, no env, so a static import is safe above the dotenv call below --
// same reasoning as hex-spec. See that module on why the list lives in one place.
import {
  NEEDS_SUPPORT_NAMES,
  SUPPORT_NOTE,
  SUPPORT_SLICER_NOTE,
} from "../src/lib/hex-support";
// Plain data, no env -- same reasoning again. The per-release LICENSE.txt.
import { hexLicenseTxt } from "../src/lib/hex-license-txt";
// Plain data, no env. The README's 2.6 safety slot, and the placeholder scan the
// --write refusal applies to every file this run would upload.
import {
  hexReadmeSafetyLines,
  ownerWordingIn,
} from "../src/lib/hex-readme-safety";

/** Hard-wrap for the archive README, which is read in Notepad and in terminals.
 *  Neither reflows, so a long sentence is either cut off at the column or
 *  scrolls sideways out of view. The academy's README module has its own copy of
 *  this for the same reason; sharing it would mean importing a module that pulls
 *  in the print spec to wrap a string. */
function wrap72(text: string, indent = ""): string[] {
  const out: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/).filter(Boolean)) {
    if (line !== "" && `${indent}${line} ${word}`.length > 72) {
      out.push(indent + line);
      line = word;
    } else {
      line = line === "" ? word : `${line} ${word}`;
    }
  }
  if (line !== "") out.push(indent + line);
  return out;
}

// Dynamic imports inside main() so dotenv populates process.env BEFORE
// src/env.ts validates it at module-eval time (a static import would hoist
// above loadEnv and fail on every var). Same shape as the other scripts here.
type R2Mod = typeof import("../src/lib/r2");
type EnvMod = typeof import("../src/env");

// The mesh set is generated in the PRIVATE hex-cluster repo (a sibling
// checkout), so this is a path out of the tree rather than a repo asset.
const SOURCE_DIR = resolve(
  process.env.PRINTABLES_DIR ?? "../hex-cluster/build/printables",
);

// Immutable release segment. Override to re-cut without clobbering a published
// URL; bump it whenever the meshes change.
//
// DERIVED FROM `HEX_RELEASE`, NOT SPELLED AGAIN. It used to be a literal, and
// the literal said "2026-07-31" long after 2026-08-03 had shipped -- 08-03 was
// published by passing PRINTABLES_RELEASE on the command line and nobody came
// back for the default. So running this script the obvious way would have
// written a fresh cut into a SUPERSEDED release prefix: the keys 08-03 links
// point at would be untouched, the new meshes would land where nothing reads
// them, and the only symptom is a release that appears to upload fine and
// changes nothing.
//
// `hex-spec.test.ts` carried a row captioned "match what upload-printables.ts
// stamps", which pinned `HEX_RELEASE` to a literal and never looked at this
// file at all -- a pin between a constant and itself. Reading the constant
// directly is the version of that intention which cannot drift.
//
// The env override stays, because re-cutting to a scratch prefix without
// touching the app's notion of the current release is a real thing to want.
const RELEASE = process.env.PRINTABLES_RELEASE ?? HEX_RELEASE;

// EVERYTHING SHIPS FREE, as one set. There is deliberately no gated tier.
//
// The parts are not the moat -- the curriculum, the validated board designs and
// the configurator are. Gating enclosure furniture to protect curriculum revenue
// protects the wrong asset, and a gated subset cannot rank: Printables and
// MakerWorld surface models on downloads, makes and remixes, so a teaser set
// gets no engagement and dies. Enforcement would be thin regardless (a printed
// functional object carries thin copyright under the useful-article doctrine),
// so a gate mostly taxes honest users.
//
// Lead capture belongs on the CONFIGURATOR ("save your build" / "email me this
// build sheet"), not on the download. Someone who configured a cluster is a warm
// lead; someone who clicked download is not.
//
// Excluded from the public set on DISCLOSURE grounds -- not commercial ones. A
// carrier is shaped around its board, so publishing it publishes that board's
// footprint and connector geometry. TB-1-POWER is a BioScale-BCI program test
// board, and the academy disclosure policy keeps program specifics off public
// surfaces. Add a part here only for that reason; do not use it as a paywall.
const WITHHELD_PARTS = new Set(["TB-1-POWER"]);

const SETS: Record<
  string,
  { label: string; parts: (shipped: ManifestPart[]) => string[] }
> = {
  "hex-cluster": {
    label: "Hex Cluster modular tile system -- complete set",
    // Handed the parts that SHIP (both withholdings already applied), never the
    // raw manifest, so a set can only ever hold what passed the allow-list.
    parts: (shipped) => shipped.map((p) => p.part),
  },
};

type ManifestPart = {
  part: string;
  family: string;
  triangles: number;
  volumeMm3: number;
  bboxMm: { x: number; y: number; z: number };
  borderEdges: number;
  files: Record<string, { path: string; bytes: number; sha256: string }>;
  /** Rotations the exporter baked in to make the part print-ready. EMPTY for a
   *  part left in its CAD pose. Read by the README so it can state which of the
   *  two a downloader is holding, rather than guessing on their behalf. */
  printOrientation?: { axis: string; degrees: number }[];
  /** Whether a human has checked that rotation. False everywhere as of release
   *  2026-07-31, which is exactly why the README says to verify before slicing. */
  printOrientationReviewed?: boolean;
};
type Manifest = { parts: ManifestPart[]; failures: unknown[] };

// Arguments are parsed STRICTLY. An unknown flag is an error, not a no-op: the
// old `--force` in particular must fail loudly for anyone whose muscle memory
// still types it, rather than be silently ignored while they assume it applied.
function parseArgs(argv: string[]): { write: boolean; allowList?: string } {
  let write = false;
  let allowList: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--write") write = true;
    else if (a === "--allow-list") {
      allowList = argv[++i];
      if (!allowList) throw new Error("--allow-list needs a path");
    } else if (a.startsWith("--allow-list=")) {
      allowList = a.slice("--allow-list=".length);
    } else {
      throw new Error(
        `Unknown argument ${JSON.stringify(a)}. Accepted: --allow-list <file>, --write.` +
          (a === "--force"
            ? "\n--force was removed: a published key is never overwritten. Cut a new release instead."
            : ""),
      );
    }
  }
  return { write, allowList };
}

let write = false;
// Where a DRY RUN drops the bytes it would have uploaded, so the archive can be
// read before it is published. Release keys are immutable and carry a one-year
// `immutable` cache header, so a wrong README is not editable afterwards -- it
// costs a whole new release segment. A dry run that only prints key names cannot
// catch that; one you can open can.
const emitDir = process.env.PRINTABLES_EMIT;

// The publish is ~170 objects and 60 MB over one TLS session, and the first two
// real runs both died partway with `ssl3_read_bytes: tls alert bad record mac`
// at different objects. Without a retry AND a skip, every attempt restarts from
// zero and the publish becomes a coin flip that gets more expensive each throw.
//
// Skipping is safe precisely because the keys are IMMUTABLE and each object
// carries the SHA-256 of its bytes: a key whose stored hash equals ours holds
// exactly the bytes this run would write. It used to compare SIZE, which a
// one-byte edit (a README typo fixed in place) passes -- so a rerun silently
// kept the old bytes. A key with a DIFFERENT hash is now a refusal, never an
// overwrite and never a skip.
const MAX_ATTEMPTS = 5;
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function loadManifest(): Manifest {
  const path = join(SOURCE_DIR, "manifest.json");
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Manifest;
  } catch {
    throw new Error(
      `No manifest at ${path}. Generate it first:\n` +
        `  cd <hardware repo>/enclosure && python tools/build_printables.py`,
    );
  }
}

let r2!: R2Mod["r2"];
let env!: EnvMod["env"];

const sha256 = (b: Buffer) => createHash("sha256").update(b).digest("hex");

type Planned = {
  key: string;
  body: Buffer;
  contentType: string;
  sha256: string;
};

function plan(key: string, body: Buffer, contentType: string): Planned {
  return { key, body, contentType, sha256: sha256(body) };
}

/** What a HEAD says about a key. Only a 404 means "absent". Every other error
 *  (403, 5xx, a TLS drop) is FATAL: the old code read ANY failure as "absent"
 *  and uploaded over whatever was there, so an expired token looked exactly
 *  like an empty bucket. A stored hash that differs, or no stored hash at all,
 *  refuses -- neither proves the published bytes are the ones we hold. */
async function headState(p: Planned): Promise<"absent" | "same"> {
  let out;
  try {
    out = await r2.send(
      new HeadObjectCommand({ Bucket: env.R2_BUCKET!, Key: p.key }),
    );
  } catch (err) {
    const status = (err as { $metadata?: { httpStatusCode?: number } })
      ?.$metadata?.httpStatusCode;
    if (status === 404) return "absent";
    const msg =
      err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    throw new Error(
      `HEAD ${p.key} failed (status ${status ?? "none"}; ${msg}). ` +
        `Only a 404 means absent, so nothing was written.`,
    );
  }
  const stored = out.Metadata?.sha256;
  if (stored === p.sha256) return "same";
  throw new Error(
    `${p.key} is already published with ${stored ? `sha256 ${stored}` : "no stored sha256"}, ` +
      `but this run's bytes hash to ${p.sha256}. Published keys are immutable, so ` +
      `this refuses and nothing was written. Cut a new release (PRINTABLES_RELEASE) instead.`,
  );
}

let skipped = 0;
let retried = 0;

async function putObject(p: Planned) {
  const kb = `${(p.body.length / 1024).toFixed(0)} KB`;
  const filename = p.key.split("/").pop()!;
  for (let attempt = 1; ; attempt++) {
    try {
      await r2.send(
        new PutObjectCommand({
          Bucket: env.R2_BUCKET!,
          Key: p.key,
          Body: p.body,
          ContentType: p.contentType,
          // Every object is a download, never something a browser renders
          // inline (the LICENSE and a .step are both text a browser would show).
          ContentDisposition: `attachment; filename="${filename}"`,
          // Sent as x-amz-meta-sha256. What the next run's HEAD compares.
          Metadata: { sha256: p.sha256 },
          // Immutable keys (see printableKey) make a long cache safe.
          CacheControl: "public, max-age=31536000, immutable",
        }),
      );
      console.log(`  [put] ${p.key}  (${kb})`);
      return;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (attempt >= MAX_ATTEMPTS) {
        throw new Error(
          `${p.key} failed after ${MAX_ATTEMPTS} attempts: ${msg}\n` +
            `Re-run the same command; published objects are skipped, so it resumes.`,
        );
      }
      retried++;
      const wait = 400 * 2 ** (attempt - 1);
      console.log(`  [retry ${attempt}/${MAX_ATTEMPTS - 1}] ${p.key}: ${msg}`);
      await sleep(wait);
    }
  }
}

/** Dry run: print (and, with PRINTABLES_EMIT, write out) every object, and make
 *  NO call to R2 at all, not even a HEAD. Write: HEAD EVERY key first, so a
 *  conflict or a HEAD error anywhere refuses before the first byte lands, then
 *  PUT only the absent ones. */
async function publish(objects: Planned[]) {
  for (const p of objects) {
    if (isManifestPath(p.key)) {
      throw new Error(`Refusing ${p.key}: manifest.json is never uploaded.`);
    }
  }

  if (!write) {
    for (const p of objects) {
      if (emitDir) {
        const dest = join(emitDir, p.key);
        mkdirSync(dirname(dest), { recursive: true });
        writeFileSync(dest, p.body);
      }
      const kb = `${(p.body.length / 1024).toFixed(0)} KB`;
      console.log(`  [dry] ${p.key}  (${kb}, sha256 ${p.sha256})`);
    }
    return;
  }

  console.log("\n-- preflight: HEAD every key --");
  const toPut: Planned[] = [];
  for (const p of objects) {
    if ((await headState(p)) === "same") {
      skipped++;
      console.log(`  [skip] ${p.key}  (already published, same sha256)`);
    } else {
      toPut.push(p);
    }
  }
  console.log(`\n-- upload: ${toPut.length} object(s) --`);
  for (const p of toPut) await putObject(p);
}

/** The only formats that go inside a set zip (plan 1.3). */
const ZIP_FORMATS = ["3mf"] as const;

const CONTENT_TYPE: Record<string, string> = {
  "3mf": "model/3mf",
  stl: "model/stl",
  step: "application/step",
};

async function main() {
  const args = parseArgs(process.argv.slice(2));
  write = args.write;
  const allowListPath = args.allowList || process.env.PRINTABLES_ALLOWLIST;

  const r2mod = await import("../src/lib/r2");
  ({ env } = await import("../src/env"));
  r2 = r2mod.r2;
  const { printableKey, printableLicenseKey, printableSetKey } = r2mod;

  if (!env.R2_ENABLED || !env.R2_BUCKET) {
    throw new Error(
      "R2 is not configured (R2_ENABLED / R2_BUCKET). Refusing to run.",
    );
  }
  if (!allowListPath) {
    throw new Error(
      "No allow-list. Pass --allow-list <file> (or set PRINTABLES_ALLOWLIST). " +
        "Nothing is uploaded without one; format in scripts/lib/printables-allowlist.ts.",
    );
  }

  const manifest = loadManifest();
  const allow = loadAllowList(resolve(allowListPath));
  console.log(`source:  ${SOURCE_DIR}`);
  console.log(`release: ${RELEASE}`);
  console.log(`bucket:  ${env.R2_BUCKET}`);
  console.log(`allow:   ${resolve(allowListPath)} (${allow.files.length} file(s))`);
  console.log(
    `mode:    ${write ? "WRITE (uploads to the real bucket)" : "DRY RUN"}`,
  );
  console.log(`parts:   ${manifest.parts.length}`);

  if (allow.release !== RELEASE) {
    throw new Error(
      `Allow-list is for release ${allow.release}, but this run cuts ${RELEASE}. Refusing.`,
    );
  }

  // A part that failed the watertight gate is absent from the manifest, so it
  // can never reach the bucket by accident. Say so out loud anyway -- a silently
  // short set is exactly the kind of thing that ships unnoticed.
  if (manifest.failures.length) {
    console.log(
      `\n!! ${manifest.failures.length} source(s) FAILED the export gate and are NOT included.` +
        `\n   Fix those before publishing, or the set is incomplete.`,
    );
  }

  const withheld = manifest.parts.filter((p) => WITHHELD_PARTS.has(p.part));
  if (withheld.length) {
    console.log(
      `\nwithheld (disclosure, not paywall): ${withheld.map((p) => p.part).join(", ")}`,
    );
  }

  // The allow-list's own withholdings (decision 1.6 and the licence rule, as the
  // release-table generator recorded them). Each is skipped BY NAME, with its
  // reason printed; a part the manifest has and the list neither lists nor
  // withholds still falls through to the check below and refuses.
  const listWithheld = new Map(allow.withheld.map((w) => [w.part, w.reason]));
  const skippedByList = manifest.parts.filter((p) => listWithheld.has(p.part));
  if (skippedByList.length) {
    console.log(
      `\nwithheld by the allow-list (${skippedByList.length}), not uploaded:`,
    );
    for (const p of skippedByList) {
      console.log(`  - ${p.part}: ${listWithheld.get(p.part)}`);
    }
  }
  const absentWithheld = allow.withheld.filter(
    (w) => !manifest.parts.some((p) => p.part === w.part),
  );
  if (absentWithheld.length) {
    console.log(
      `withheld names not in this manifest (nothing to skip): ${absentWithheld.map((w) => w.part).join(", ")}`,
    );
  }

  // EVERY SOURCE FILE this run would read into the bucket, checked against the
  // allow-list BEFORE a single object is planned. Refusal is all-or-nothing.
  const shipped = manifest.parts.filter(
    (p) => !WITHHELD_PARTS.has(p.part) && !listWithheld.has(p.part),
  );
  const problems = checkAgainstAllowList(
    shipped.flatMap((p) =>
      Object.values(p.files).map((f) => ({ path: f.path, part: p.part })),
    ),
    allow,
  );
  for (const p of shipped) {
    for (const fmt of Object.keys(p.files)) {
      if (!CONTENT_TYPE[fmt]) problems.push(`${p.part}: unknown format "${fmt}"`);
    }
  }
  if (problems.length > 0) {
    throw new Error(
      `Refusing: the upload does not match the allow-list (${problems.length} problem(s)):\n` +
        problems.map((e) => `  - ${e}`).join("\n"),
    );
  }

  const objects: Planned[] = [];
  // Everything this run would publish, as the bytes a reader would open: each
  // standalone object, and each zip ENTRY before compression (a marker inside a
  // deflated README is not findable in the zip's own bytes).
  const scan: { name: string; data: Buffer | string }[] = [];

  // Standalone too, not just inside the zip: anyone grabbing a single .3mf by
  // URL never opens the archive, and CC BY only works if the terms travel.
  objects.push(
    plan(
      printableLicenseKey(RELEASE),
      Buffer.from(LICENSE_TXT, "utf8"),
      "text/plain; charset=utf-8",
    ),
  );

  for (const part of shipped) {
    for (const [format, file] of Object.entries(part.files)) {
      const fmt = format as "3mf" | "stl" | "step";
      objects.push(
        plan(
          printableKey(RELEASE, fmt, part.part, fmt),
          readFileSync(join(SOURCE_DIR, file.path)),
          CONTENT_TYPE[fmt],
        ),
      );
    }
  }

  // A FIXED timestamp on every zip entry. JSZip otherwise stamps "now", so the
  // same inputs produced a different archive on every run -- harmless while the
  // skip compared sizes, fatal now that it compares hashes: a rerun after a
  // dropped connection would find its own half-published zip "changed" and
  // refuse. Derived from the release id, so a release's archive is reproducible.
  // `createFolders: false` matters as much as the date: by default JSZip adds a
  // `3mf/` and `stl/` directory entry for each path, and stamps THOSE with "now"
  // whatever date the file entry carries. Extractors create the folders from the
  // file paths regardless, so the entries carry nothing.
  const zipDate = new Date(`${RELEASE}T00:00:00Z`);
  const entryDate = Number.isNaN(zipDate.getTime())
    ? new Date("1980-01-01T00:00:00Z")
    : zipDate;

  for (const [setName, set] of Object.entries(SETS)) {
    const names = set.parts(shipped);
    const zip = new JSZip();
    const zipKey = printableSetKey(RELEASE, setName);
    const add = (name: string, data: string | Buffer) => {
      scan.push({ name: `${zipKey} > ${name}`, data });
      zip.file(name, data, { date: entryDate, createFolders: false });
    };
    // The README describes the parts it actually ships with, so it is handed
    // the manifest rows for exactly those names, not the whole manifest.
    const setParts = manifest.parts.filter((p) => names.includes(p.part));
    add("README.txt", setReadme(set.label, names, setParts));
    add("LICENSE.txt", LICENSE_TXT);
    for (const name of names) {
      const part = manifest.parts.find((p) => p.part === name);
      if (!part) continue;
      // 3MF ONLY (owner decision, launch plan 1.3). STL and STEP stay per-part
      // downloads and never go in the zip: 3MF carries units and part names, and
      // bundling the fallbacks would double the archive for no print value.
      for (const fmt of ZIP_FORMATS) {
        const file = part.files[fmt];
        if (!file) continue;
        add(`${fmt}/${name}.${fmt}`, readFileSync(join(SOURCE_DIR, file.path)));
      }
    }
    const body = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
    });
    console.log(`  set ${setName}: ${names.length} part(s)`);
    objects.push(plan(zipKey, body, "application/zip"));
  }

  // OWNER PLACEHOLDERS, in ANY file. The LICENSE disclaimer (6.8) and the README
  // safety text (2.6) are the owner's words, and a release key is immutable, so
  // publishing a placeholder is permanent. Checked after planning so it sees the
  // exact bytes, and before publish() so it lands before any R2 call. A dry run
  // reports them and carries on: it exists so the slots can be read.
  for (const p of objects) {
    if (p.contentType !== "application/zip") {
      scan.push({ name: p.key, data: p.body });
    }
  }
  const pending = scan.flatMap(({ name, data }) =>
    ownerWordingIn(data).map((m) => `${name}: ${m}`),
  );
  if (pending.length) {
    if (write) {
      throw new Error(
        `Refusing --write: the release still carries owner placeholders (${pending.length}):\n  ` +
          pending.join("\n  ") +
          `\nReplace them (src/lib/hex-license-txt.ts, src/lib/hex-readme-safety.ts) before --write.`,
      );
    }
    console.log(
      `\n!! ${pending.length} owner placeholder(s) remain; --write will refuse until they are replaced:\n  ` +
        pending.join("\n  "),
    );
  }

  await publish(objects);

  const base = env.NEXT_PUBLIC_R2_PUBLIC_BASE_URL;
  console.log(
    `\n${write ? "Uploaded" : "Would upload"} release ${RELEASE}.` +
      (write
        ? `\nskipped (already published): ${skipped} · retries: ${retried}`
        : "") +
      (base
        ? `\nPublic base: ${base}/printables/${RELEASE}/`
        : write
          ? `\nNo R2 custom domain set, so the files serve through /api/printable/${RELEASE}/...`
          : ""),
  );
  if (!write) console.log("Re-run with --write to apply.");
}

// The README is deliberately plain ASCII (it uses `--` for dashes throughout),
// because it is read in whatever the downloader's zip viewer or Notepad does
// with encodings. The shared spec is written for the WEB page, so degree signs,
// en dashes and multiplication signs come through it; fold them here rather
// than ASCII-ifying the page.
function ascii(s: string): string {
  return s
    .replace(/°/g, " deg ")
    .replace(/[–—]/g, "-")
    .replace(/×/g, "x")
    .replace(/\s+/g, " ")
    .trim();
}

/** How the shipped meshes are posed, stated from the manifest rather than
 *  asserted. Splits the set into "already rotated for printing" and "still in
 *  its CAD pose", and says plainly whether a human has checked either. */
function orientationNote(parts: ManifestPart[]): string[] {
  const rotated = parts.filter((p) => (p.printOrientation?.length ?? 0) > 0);
  const reviewed = parts.filter((p) => p.printOrientationReviewed);
  const total = parts.length;

  if (rotated.length === 0) {
    return [
      "Every part is exported in its CAD orientation. Check each one sits on a",
      "flat face before slicing.",
    ];
  }

  const lines = [
    `Orientation: ${rotated.length} of the ${total} parts are exported already`,
    `rotated for printing; the remaining ${total - rotated.length} are in their CAD`,
    "orientation.",
  ];
  if (reviewed.length < rotated.length) {
    lines.push(
      "",
      "Those rotations are derived automatically and have NOT been reviewed by",
      "hand. Check every part sits on a flat face before slicing.",
    );
  } else {
    // "Except the parts named below" only when a support section follows. It
    // used to say "the two exceptions below" unconditionally, and the v2 set has
    // no part in NEEDS_SUPPORT_NAMES, so the sentence pointed at a section that
    // never rendered. Support data stays unknown until launch item 4.7.
    lines.push(
      "",
      ...wrap72(
        (supportParts(parts).length > 0
          ? "Every orientation has been checked: each part rests on a flat face, " +
            "except the parts named below."
          : "Every orientation has been checked: each part rests on a flat face.") +
          " Nobody has printed the set yet, so this is a geometric check and not " +
          "a print-tested one.",
      ),
    );
  }

  // The parts that rest on a line by DESIGN, named so nobody is surprised
  // mid-print. The list used to be a local const here AND a second one in
  // src/lib/hex-pack-readme.ts, each asking the other to be kept in sync. It now
  // lives once in @/lib/hex-support, because the download endpoint reads the same
  // set to decide whether a single-plate build ships bare or inside an archive --
  // so a re-cut that updated this file and not that one would ship a bare file
  // with no warning in it at all. See that module's header.
  const present = supportParts(parts);
  if (present.length > 0) {
    lines.push(
      "",
      `Support required -- ${present.join(", ")}.`,
      "These lie on their side on purpose: a spike carries its load along its",
      "axis, so printed upright the layers stack along that load and peel apart.",
      "Lying down runs them ACROSS it. What that costs is what they stand on, and",
      "it is not the same for both. Every other part stands on a flat face.",
      "",
    );
    // ONE ENTRY PER PART. The old note gave both the same sentence and sent
    // everyone to a brim, which cannot hold a part with no perimeter on the
    // plate. The measured figures live beside the list in src/lib/hex-support.
    for (const name of present) {
      const note = SUPPORT_NOTE[name];
      if (note) lines.push(...wrap72(`${name} ${note}`, "  "));
    }
    lines.push("", ...wrap72(SUPPORT_SLICER_NOTE, ""));
  }
  return lines;
}

/** The shipped parts that need support, in NEEDS_SUPPORT_NAMES order. */
function supportParts(parts: ManifestPart[]): string[] {
  return NEEDS_SUPPORT_NAMES.filter((n) => parts.some((p) => p.part === n));
}

function setReadme(
  label: string,
  names: string[],
  parts: ManifestPart[],
): string {
  return [
    `${label}`,
    "",
    "Hex Cluster modular tile system -- One Thousand Drones, LLC",
    "https://academy.onethousanddrones.com/hex",
    "",
    // Decision 1.10: the configurator's own host, live before any public link.
    "Configure a cluster and generate a build sheet:",
    "  https://hex.onethousanddrones.com",
    "",
    "Format: 3mf/ (carries units and part names). STL and STEP are",
    "        separate per-part downloads, not in this archive.",
    "",
    // CORRECTED 2026-08-02. The 2026-07-31 release says "Printed in PLA at
    // 0.2 mm". The material is PETG, and the 0.25 mm design gap is toleranced
    // against PETG shrinkage, so it is not a free choice. That release is
    // immutable and stays wrong -- the /hex page is the authority, and this
    // text is corrected for the NEXT release. Composed from the SHARED spec
    // module so the archive and the page cannot drift apart.
    "Print settings:",
    // ======================================================================
    // THESE TWO ROWS ARE NOW DERIVED, AND THIS README IS IMMUTABLE.
    // ======================================================================
    // `HEX_PRINT_PARAMS` used to hardcode `Perimeters` and `Infill`. They now
    // derive from `PRINT_INTENT_TABLE`, which is what stops the /hex card, both
    // archive READMEs and the downloaded plate from disagreeing.
    //
    // The cost lands HERE, and it is easy to miss: this README is PUT to R2
    // under `public, max-age=31536000, immutable`, inside a release prefix that
    // is never overwritten. So the text below is frozen at publish time, while
    // the table it derives from is not.
    //
    // CONSEQUENCE: editing `PRINT_INTENT_TABLE` makes every ALREADY-PUBLISHED
    // release's README disagree with every newly generated plate, silently, and
    // nothing anywhere compares an R2 object against the running code.
    //
    // ==================================================================
    // DECIDED, 2026-08-18 (owner): A RELEASE BUMP IS **NOT** REQUIRED.
    // ==================================================================
    // Pre-V1. No users, no configs in the wild -- so there is nobody holding a
    // published release whose README could contradict what they download today.
    // Editing the table is free RIGHT NOW, and re-cutting 161 objects to correct
    // a sentence would be ceremony rather than care.
    //
    // WHAT ENDS THIS, and it is not a date. The moment a published release is in
    // someone's hands -- the first real download of a release segment we do not
    // control, the first saved build whose sheet cites one, V1 -- the trade
    // inverts: an immutable README is then a promise made to a person, and the
    // only ways to keep it are a new segment or an explicit correction. Whoever
    // notices that has happened owns re-opening this comment.
    //
    // Recorded rather than deleted on purpose. A warning that is simply removed
    // reads later as an oversight nobody weighed; this one was weighed, and the
    // condition it was weighed under is written down beside it.
    ...HEX_PRINT_PARAMS.map(
      (p) =>
        `  ${p.label}: ${ascii(p.value)}${p.aside ? ` (${ascii(p.aside)})` : ""}`,
    ),
    ...HEX_CLEARANCE.map(
      (p) =>
        `  ${p.label}: ${ascii(p.value)}${p.aside ? ` (${ascii(p.aside)})` : ""}`,
    ),
    "",
    `Hex bases print ${HEX_ORIENTATION.value}. ${ascii(HEX_ORIENTATION.why)}`,
    "",
    // CORRECTED 2026-08-03. The 2026-07-31 release says flatly that "parts are
    // exported in their CAD orientation". That is wrong for a third of the set:
    // 16 of the 53 carry a baked -90 degree X rotation from the exporter. Worse,
    // it points the reader at the wrong risk. The risk is not that nothing was
    // rotated, it is that the rotations are DERIVED and every part in the
    // manifest still has printOrientationReviewed = false. Counted from the
    // manifest rather than typed in, so the sentence cannot drift from the set.
    ...orientationNote(parts),
    "",
    // Launch item 2.6. The owner's (and a lawyer's) words, not drafted here; a
    // marked slot until then, and --write refuses while the marker is present.
    ...hexReadmeSafetyLines(),
    "",
    "Full spec: https://academy.onethousanddrones.com/hex",
    "",
    `Parts (${names.length}):`,
    ...names.map((n) => `  - ${n}`),
    "",
    "Licensed CC BY 4.0 -- see LICENSE.txt.",
  ].join("\n");
}

// CC BY 4.0: attribution is the only condition. Chosen deliberately over NC/SA.
// The parts are not the moat, enforcement against a functional printed object is
// thin under the useful-article doctrine, and both NC and SA suppress the remix
// volume that makes a listing rank. Mandated attribution IS the return here.
//
// NOTE: this is one-way. Files published under CC BY stay CC BY; only future
// releases can carry different terms.
//
// The text is chosen PER RELEASE in `src/lib/hex-license-txt.ts`: the three
// published v1 releases get their published bytes back verbatim (pinned by
// sha256 in its test), and a later release gets the v2 notice with its year and
// the owner's disclaimer slot.
const LICENSE_TXT = hexLicenseTxt(RELEASE);

// Exported so the test can await the whole run and observe the exit code. A
// refusal of ANY kind (allow-list, hash conflict, HEAD error) lands here and
// exits non-zero.
export const finished = main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
