// Package + upload the hex-cluster printables to R2.
//
//   pnpm tsx scripts/upload-printables.ts            # DRY RUN (default)
//   pnpm tsx scripts/upload-printables.ts --write    # actually uploads
//
// Reads the mesh set generated by the PRIVATE hardware repo
// (`otd-dev-hardware/enclosure/tools/build_printables.py`) and pushes it to R2
// under an immutable `printables/{release}/...` prefix. The .FCStd sources stay
// private; only generated meshes ship.
//
// !! THERE IS NO LOCAL R2. !!
// Unlike the database — where `.env.local` points at local Postgres since
// 2026-07-15, so scripts are safe by default — R2_* credentials in `.env.local`
// are the REAL bucket. `--write` therefore uploads to production storage. Hence
// dry run is the default and prints every object it would put, matching the
// convention in scripts/import-content.ts.
//
// Set membership below is a PROPOSAL pending the owner's call on what is free
// vs gated. Edit SETS, not the upload logic.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import JSZip from "jszip";
import { PutObjectCommand } from "@aws-sdk/client-s3";

// Dynamic imports inside main() so dotenv populates process.env BEFORE
// src/env.ts validates it at module-eval time (a static import would hoist
// above loadEnv and fail on every var). Same shape as the other scripts here.
type R2Mod = typeof import("../src/lib/r2");
type EnvMod = typeof import("../src/env");

const SOURCE_DIR = resolve(
  process.env.PRINTABLES_DIR ?? "../otd/hardware/enclosure/build/printables",
);

// Immutable release segment. Override to re-cut without clobbering a published
// URL; bump it whenever the meshes change.
const RELEASE = process.env.PRINTABLES_RELEASE ?? "2026-07-31";

// EVERYTHING SHIPS FREE, as one set. There is deliberately no gated tier.
//
// The parts are not the moat -- the curriculum, the validated board designs and
// the configurator are. Gating enclosure furniture to protect curriculum revenue
// protects the wrong asset, and a gated subset cannot rank: Printables and
// MakerWorld surface models on downloads, makes and remixes, so a teaser set
// gets no engagement and dies. Enforcement would be thin regardless (a printed
// functional object carries thin copyright under the useful-article doctrine),
// so a gate mostly taxes honest users.
//
// Lead capture belongs on the CONFIGURATOR ("save your build" / "email me this
// build sheet"), not on the download. Someone who configured a cluster is a warm
// lead; someone who clicked download is not.
//
// Excluded from the public set on DISCLOSURE grounds -- not commercial ones. A
// carrier is shaped around its board, so publishing it publishes that board's
// footprint and connector geometry. TB-1-POWER is a BioScale-BCI program test
// board, and the academy disclosure policy keeps program specifics off public
// surfaces. Add a part here only for that reason; do not use it as a paywall.
const WITHHELD_PARTS = new Set(["TB-1-POWER"]);

const SETS: Record<string, { label: string; parts: (m: Manifest) => string[] }> = {
  "hex-cluster": {
    label: "Hex Cluster modular tile system -- complete set",
    parts: (m) => m.parts.map((p) => p.part).filter((p) => !WITHHELD_PARTS.has(p)),
  },
};

type ManifestPart = {
  part: string;
  family: string;
  triangles: number;
  volumeMm3: number;
  bboxMm: { x: number; y: number; z: number };
  borderEdges: number;
  files: Record<string, { path: string; bytes: number; sha256: string }>;
};
type Manifest = { parts: ManifestPart[]; failures: unknown[] };

const write = process.argv.includes("--write");

function loadManifest(): Manifest {
  const path = join(SOURCE_DIR, "manifest.json");
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Manifest;
  } catch {
    throw new Error(
      `No manifest at ${path}. Generate it first:\n` +
        `  cd <hardware repo>/enclosure && python tools/build_printables.py`,
    );
  }
}

let r2!: R2Mod["r2"];
let env!: EnvMod["env"];

async function put(key: string, body: Buffer, contentType: string) {
  if (!write) {
    console.log(`  [dry] ${key}  (${(body.length / 1024).toFixed(0)} KB)`);
    return;
  }
  await r2.send(
    new PutObjectCommand({
      Bucket: env.R2_BUCKET!,
      Key: key,
      Body: body,
      ContentType: contentType,
      // Immutable keys (see printableKey) make a long cache safe.
      CacheControl: "public, max-age=31536000, immutable",
    }),
  );
  console.log(`  [put] ${key}  (${(body.length / 1024).toFixed(0)} KB)`);
}

const CONTENT_TYPE: Record<string, string> = {
  "3mf": "model/3mf",
  stl: "model/stl",
  step: "application/step",
};

async function main() {
  const r2mod = await import("../src/lib/r2");
  ({ env } = await import("../src/env"));
  r2 = r2mod.r2;
  const { printableKey, printableSetKey } = r2mod;

  if (!env.R2_ENABLED || !env.R2_BUCKET) {
    throw new Error("R2 is not configured (R2_ENABLED / R2_BUCKET). Refusing to run.");
  }

  const manifest = loadManifest();
  console.log(`source:  ${SOURCE_DIR}`);
  console.log(`release: ${RELEASE}`);
  console.log(`bucket:  ${env.R2_BUCKET}`);
  console.log(`mode:    ${write ? "WRITE (uploads to the real bucket)" : "DRY RUN"}`);
  console.log(`parts:   ${manifest.parts.length}`);

  // A part that failed the watertight gate is absent from the manifest, so it
  // can never reach the bucket by accident. Say so out loud anyway -- a silently
  // short set is exactly the kind of thing that ships unnoticed.
  if (manifest.failures.length) {
    console.log(
      `\n!! ${manifest.failures.length} source(s) FAILED the export gate and are NOT included.` +
        `\n   Fix those before publishing, or the set is incomplete.`,
    );
  }

  const withheld = manifest.parts.filter((p) => WITHHELD_PARTS.has(p.part));
  if (withheld.length) {
    console.log(
      `\nwithheld (disclosure, not paywall): ${withheld.map((p) => p.part).join(", ")}`,
    );
  }

  console.log("\n-- individual files --");
  for (const part of manifest.parts) {
    if (WITHHELD_PARTS.has(part.part)) continue;
    for (const [format, file] of Object.entries(part.files)) {
      const fmt = format as "3mf" | "stl" | "step";
      const body = readFileSync(join(SOURCE_DIR, file.path));
      await put(printableKey(RELEASE, fmt, part.part, fmt), body, CONTENT_TYPE[fmt]);
    }
  }

  console.log("\n-- set archives --");
  for (const [setName, set] of Object.entries(SETS)) {
    const names = set.parts(manifest);
    const zip = new JSZip();
    zip.file("README.txt", setReadme(set.label, names));
    for (const name of names) {
      const part = manifest.parts.find((p) => p.part === name);
      if (!part) continue;
      // 3MF + STL only. STEP is the archival/remix format and stays a
      // per-file download; bundling it would double the zip for no print value.
      for (const fmt of ["3mf", "stl"] as const) {
        const file = part.files[fmt];
        if (!file) continue;
        zip.file(`${fmt}/${name}.${fmt}`, readFileSync(join(SOURCE_DIR, file.path)));
      }
    }
    const body = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    console.log(`  ${setName}: ${names.length} part(s)`);
    await put(printableSetKey(RELEASE, setName), body, "application/zip");
  }

  const base = env.NEXT_PUBLIC_R2_PUBLIC_BASE_URL;
  console.log(
    `\n${write ? "Uploaded" : "Would upload"} release ${RELEASE}.` +
      (base ? `\nPublic base: ${base}/printables/${RELEASE}/` : ""),
  );
  if (!write) console.log("Re-run with --write to apply.");
}

function setReadme(label: string, names: string[]): string {
  return [
    `${label}`,
    "",
    "Hex Cluster modular tile system -- One Thousand Drones, LLC",
    "https://academy.onethousanddrones.com/hex",
    "",
    "Configure a cluster and generate a build sheet:",
    "  https://demo.onethousanddrones.com/hex",
    "",
    "Formats: 3mf/ (recommended -- carries units and part names)",
    "         stl/ (universal fallback)",
    "",
    `Parts (${names.length}):`,
    ...names.map((n) => `  - ${n}`),
    "",
    "LICENSE: see LICENSE.txt in this archive.",
  ].join("\n");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
