// Tests for the pure KiCad metadata extractor (Stage C enhancement).
//
// `extractKicadMeta` reads a KiCad symbol (.kicad_sym) or footprint (.kicad_mod)
// text and pulls two best-effort, human-reviewable suggestions:
//   - `ref`    — the first symbol/footprint NAME (deterministic, reliable).
//   - `source` — the generator (SnapEDA / SamacSys / Ultra Librarian), set ONLY
//                when EXACTLY ONE distinct generator is detected (else undefined).
//
// The module is PURE (imported by the client AssetUpload island): no DB/env/I/O.
// It must never throw — empty/garbage/non-KiCad input returns `{}`.

import { describe, expect, test } from "vitest";
import { extractKicadMeta } from "@/lib/kicad-meta";

describe("extractKicadMeta — ref", () => {
  test("extracts the symbol name from a .kicad_sym snippet", () => {
    const text = `(kicad_symbol_lib (version 20211014) (generator kicad_symbol_editor)
  (symbol "AP2112K-3.3" (in_bom yes) (on_board yes)
    (property "Reference" "U" (at 0 0 0))
  )
)`;
    expect(extractKicadMeta(text).ref).toBe("AP2112K-3.3");
  });

  test("extracts the footprint name from a .kicad_mod snippet", () => {
    const text = `(footprint "SOP65P640X120-8N" (layer "F.Cu")
  (attr smd)
  (fp_text reference "REF**" (at 0 0))
)`;
    expect(extractKicadMeta(text).ref).toBe("SOP65P640X120-8N");
  });

  test("extracts the name from an older unquoted (module NAME ...) form", () => {
    const text = `(module MyFP (layer F.Cu) (tedit 5A1B2C3D)
  (fp_text reference REF** (at 0 0) (layer F.SilkS))
)`;
    expect(extractKicadMeta(text).ref).toBe("MyFP");
  });

  test("extracts the name from a QUOTED legacy (module \"NAME\" ...) form", () => {
    const text = `(module "MyFP" (layer F.Cu) (tedit 5A1B2C3D)
  (fp_text reference REF** (at 0 0) (layer F.SilkS))
)`;
    expect(extractKicadMeta(text).ref).toBe("MyFP");
  });

  test("returns undefined ref when no symbol/footprint/module is present", () => {
    expect(extractKicadMeta("(some_other_sexpr (foo bar))").ref).toBeUndefined();
  });

  test("a malformed footprint with NO quoted name yields undefined ref (not '(layer')", () => {
    const text = `(footprint (layer "F.Cu") (attr smd)
  (fp_text reference "REF**" (at 0 0))
)`;
    const ref = extractKicadMeta(text).ref;
    expect(ref).toBeUndefined();
    expect(ref).not.toBe("(layer");
    expect(ref).not.toBe("layer");
  });

  test("a normal quoted footprint still returns its real name", () => {
    const text = `(footprint "REAL_NAME" (layer "F.Cu") (attr smd))`;
    expect(extractKicadMeta(text).ref).toBe("REAL_NAME");
  });

  test("extracts ref and source across CRLF line endings", () => {
    const text =
      `(footprint "CRLF-FP" (layer "F.Cu")\r\n` +
      `  (descr "Generated by SnapEDA")\r\n` +
      `  (attr smd)\r\n)`;
    const meta = extractKicadMeta(text);
    expect(meta.ref).toBe("CRLF-FP");
    expect(meta.source).toBe("SnapEDA");
  });
});

describe("extractKicadMeta — source", () => {
  test("detects SnapEDA", () => {
    const text = `(footprint "X" (descr "Generated by SnapEDA"))`;
    expect(extractKicadMeta(text).source).toBe("SnapEDA");
  });

  test("detects SamacSys", () => {
    const text = `(footprint "X" (descr "Created by SamacSys"))`;
    expect(extractKicadMeta(text).source).toBe("SamacSys");
  });

  test("detects SamacSys via the 'Component Search Engine' alias", () => {
    const text = `(footprint "X" (descr "Made with Component Search Engine"))`;
    expect(extractKicadMeta(text).source).toBe("SamacSys");
  });

  test("detects Ultra Librarian (with or without the space)", () => {
    const spaced = `(footprint "X" (descr "Exported from Ultra Librarian"))`;
    expect(extractKicadMeta(spaced).source).toBe("Ultra Librarian");
    const joined = `(footprint "X" (descr "ultralibrarian export"))`;
    expect(extractKicadMeta(joined).source).toBe("Ultra Librarian");
  });

  test("leaves source undefined when no generator marker is present", () => {
    const text = `(footprint "X" (descr "hand-made by a human"))`;
    expect(extractKicadMeta(text).source).toBeUndefined();
  });

  test("the SAME generator appearing twice still counts as ONE distinct hit", () => {
    const text = `(footprint "DUP-FP" (descr "Generated by SnapEDA")
  (fp_text user "SnapEDA" (at 0 0)))`;
    expect(extractKicadMeta(text).source).toBe("SnapEDA");
  });

  test("leaves source undefined when TWO different markers appear (ambiguous), but still extracts ref", () => {
    const text = `(footprint "AMBIG-FP" (descr "Generated by SnapEDA then re-tagged by SamacSys"))`;
    const meta = extractKicadMeta(text);
    expect(meta.source).toBeUndefined();
    expect(meta.ref).toBe("AMBIG-FP");
  });
});

describe("extractKicadMeta — robustness", () => {
  test("returns {} for empty input", () => {
    expect(extractKicadMeta("")).toEqual({});
  });

  test("returns {} for garbage / non-KiCad input", () => {
    expect(extractKicadMeta("not a kicad file at all !!! {}{}{}")).toEqual({});
  });
});
